### ISSUE TITLE
Passing -j0 or -j-1 means test runner hangs

### ISSUE THREAD

**Issue by chadaustin** [feuerbach/tasty#104]
If you pass -j0 or -j-1 to a test run, it doesn't actually spawn any test runners and thus the test hangs.

**Comment by feuerbach** [comment]
Sure, did you expect anything else?

**Comment by tr00per** [comment]
An error message would be good ;)

pt., 20 mar 2015, 02:23 Roman Cheplyaka użytkownik <notifications@github.com>
napisał:

**Comment by feuerbach** [comment]
Fair enough, I'd accept a PR.
