### ISSUE TITLE
SmallCheck: allow testing a property with reduced depth

### ISSUE THREAD

**Issue by Borgvall** [feuerbach/tasty#106]
I have an extreme case, where a single smallcheck property creates tens of millions different test cases (using the default depth 5). So checking this single property takes more time, than the rest of the properties combined!

It would be useful, if one can reduce the depth for certain properties. Then tasty can reasonably contain such properties in its test suite.

**Comment by feuerbach** [comment]
It's already possible, see <https://github.com/feuerbach/regex-applicative/blob/master/tests/test.hs#L181> for an example

**Comment by Borgvall** [comment]
Sorry, I looked in `Test.Tasty.Options` for a way to locally changing an option. So I missed the functions in `Test.Tasty`.
