### ISSUE TITLE
Alignment breaks with wide Asian characters

### ISSUE THREAD

**Issue by feuerbach** [feuerbach/tasty#111]
Originally [reported](https://groups.google.com/forum/#!topic/haskell-tasty/RsUDVOwWc6E) by Bongseo Jang on the mailing list.

The problem is that some characters (like [U+C774](https://codepoints.net/U+C774)) take double space in a monospaced font.

I suspect this is determined by the [EAST ASIAN WIDTH](http://www.unicode.org/reports/tr11/) property, but this needs to be confirmed yet.

**Comment by feuerbach** [comment]
See also: https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

**Comment by feuerbach** [comment]
> Except for a few characters, which are explicitly called out as fullwidth or halfwidth in the Unicode Standard, characters are not duplicated based on distinction in width. Some characters, such as the ideographs, are always wide; others are always narrow; and some can be narrow or wide, depending on the context. The Unicode character property East_Asian_Width provides a default classification of characters, which an implementation can use to decide at runtime whether to treat a character as narrow or wide.

This isn't helping :/

**Comment by tosoonee** [comment]
Why do you think it's not helping? I'm new to haskell and just want to know :-)

It seems that the width can be determined with the property East_Asian_Width, can't it? For ambiwidth, there is 'set ambiwidth=[single|double]' in vim and seems decent decision.

**Comment by feuerbach** [comment]
I was specifically referring to these parts:

> some can be narrow or wide

and

> an implementation can use to decide at runtime whether to treat a character as narrow or wide

So I don't see how I can determine how much space these characters will take on a terminal.

**Comment by feuerbach** [comment]
This seems to be difficult to fix and relatively low impact, so closing. If anyone comes up with a simple self-contained solution, I'd definitely consider it.
