### ISSUE TITLE
Non-ASCII characters fail to display in test output

### ISSUE THREAD

**Issue by sapek** [feuerbach/tasty#113]
To repro for example create a test group with non-ASCII character(s) in the name, e.g.:

    testGroup "\955" [
    -- ...
    ]

Running the test results in following error:

    <stdout>: commitBuffer: invalid argument (invalid character)

It repros on Windows, I don't know about other platforms.

**Comment by feuerbach** [comment]
Works here (on Linux):

![tasty](https://cloud.githubusercontent.com/assets/24844/8449190/f3271330-1fd7-11e5-8dcb-a1b92ddd6ea0.png)

What happens if you run

```
putStrLn "\955"
```

in ghci in a terminal?

**Comment by sapek** [comment]
```
Prelude> putStrLn "\955"
*** Exception: <stdout>: hPutChar: invalid argument (invalid character)
Prelude>
```

**Comment by feuerbach** [comment]
Ok, so not really a tasty issue.
