### ISSUE TITLE
Known-broken tests

### ISSUE THREAD

**Issue by nomeata** [feuerbach/tasty#114]
This is similar to #99, but not quite the same.

In GHC we can mark test cases as `known_broken`. This means that a failing test case does not cause the test suite to fail. If, however, the test suddenly succeeds, than *that* is a failure.

This can for example be used for test-driven development: Create the tests, mark them as `known_broken`, and whoever implements the corresponding feature will remove the marker in the process.

Possible APIs could be
    
    broken :: TestTree -> TestTree

or

    broken :: String -> TestTree -> TestTree

where the latter could include some information to be displayed along the test, e.g. a ticket number.

Such a test should be reported as `FAIL (expected)` or `FAIL (expected: …)`. If it succeeds, the reporting should be `OK (unexpected)` and it should be counted towards the total count failed tests.

**Comment by nomeata** [comment]
Ah, the difference to #99 is that with ignore is that the is not run at all.

**Comment by feuerbach** [comment]
How is this better than having a negation within the test itself?

E.g. if these are unit tests, then you assert that a the result of `ghc testcase.hs` has the exitcode of 1.

**Comment by nomeata** [comment]
Because the test itself tell how things should be. It would be weird to write

    testCase "arith" (assert (1 + 1 /= 2))

instead of 

    broken $ testCase "arith" (assert (1 + 1 == 2))

Logically equivalent, the difference in meaning (and reporting) is huge!

Also, some tests are not easily invertable. What if I have

    testCase "arith" (1 + 1 @?= 2)

– there is no `@?/=`.

**Comment by feuerbach** [comment]
Ok, I thought that you wanted to apply this to things like expected compilation errors, but apparently you want something different.

The formulation of TDD that I've come across tell that your tests should in fact fail until you've implemented the feature. Why would you want to revert that?

Are there any other applications for this apart from TDD?

**Comment by nomeata** [comment]
I want them to fail, but I want it to be different from an unexpected failure. For example, if I am adding a new (still failing) test case for a yet to be developed feature, then clearly I have improved the overall situation over the previous state: The code is still the same, but the test suite is more useful. Therefore, I’d like to be able to push this change. But clearly, for someone running `cabal test` it should not complain, just as before.

Similarly for newly reported bugs: Even before a fix is present it is useful to add a test case to the test suite, but again, that should not render `cabal test` pointless.

Here is  very recent example of this workflow in GHC: http://git.haskell.org/ghc.git/commitdiff/5dc88b72e4c3cc066e19ea5ece98ce152cd0ca25

**Comment by feuerbach** [comment]
In that case, I'd just push the changes to a branch. Then it'd only show up for the people who are only working on that feature, which is what they'd expect.

I mean, I understand that you've adopted this workflow and it works for you. But this is fairly uncommon, and I am reluctant to add and maintain such a specialized feature.

Even if you decide to adopt tasty for ghc, you won't need this as a Haskell-level function. As I understand from your link, your tests are in text files, and expect_broken is an annotation in such a file. So you won't have a tasty `testCase` per each ghc test case; instead you'd have a single (or perhaps a few) test case functions that read data from text files, launch ghc and compare the output. That function could handle the expect_broken case as well.

**Comment by nomeata** [comment]
Sorry for not being clear: I do not plan to use tasty for GHC. But I’d like to use this (IMHO very useful) workflow for my own projects. And given the variety of test case types that tasty supports, I don’t think any of the workarounds involving the definition of the test case as viable (negate a QuickCheck property? Change tasty-golden to support “everything ok but this particular file”?). Especially as having expect-broken tests reported as `OK` is a lie...

I have not seen many other test frameworks. Is it really uncommon? Seems to be too useful a feature not to have... strange.

**Comment by nomeata** [comment]
I did a small round of research with google:
Here it is in boost: http://www.boost.org/doc/libs/1_58_0/libs/test/doc/html/utf/user-guide/test-organization/expected-failures.html
Here in python: https://docs.python.org/2/library/unittest.html#unittest.expectedFailure
Here in greg, whatever that is: http://home.gna.org/greg/greg.html

So the concept is maybe not ubiquitous, but definitely not uncommon.

**Comment by feuerbach** [comment]
If we can come up with an extension point/interface that is simple, general, and allows you to implement this feature (as well as #99) as a plugin, I'd be more willing to adopt it.

**Comment by feuerbach** [comment]
Would something as simple as being able to transform the success/fail status and status text suffice?

**Comment by nomeata** [comment]
That sounds like a good idea. I guess something of type

    wrapTest :: (IO Result -> IO Result) -> TestTree -> TestTree

would go a long way. And even more if the `Result` field would get a new field `resultShortDescription :: String` that would allow a test to override this code in `ConsoleReporter`

          if resultSuccessful result
            then printFn "OK"
            else printFn "FAIL"

so that it is possible to change that to `FAIL (expected)` resp. `PASS (unexpected)`.

**Comment by nomeata** [comment]
I gave it a shot. With the code in the pull request, I get this output:
```
  Unification tests
    unify pred:          OK
    unify with ∀:        OK
    unify pred under ∀:  OK
    unify subst under ∀: OK
    regression1:         FAIL
      (unexpected success)
    regression2:         OK
      expected: 
          A: ∃y.P1(y)
          B: ∀x.P4(x)
          P1: λy.∀x.P(x,y)
          P2: λx.P(x,c)
          P3: λx.P(x,c)
          P4: λx.∃y.P(x,y)
       but got: 
          A: ∃x.P1(x)
          B: ∀x.P4(x)
          P1: λtmp.∀x.P2(x)
          P2: λtmp.P3(y2)
          P3: λtmp.P(x,y)
          P4: λtmp.∃x.P3(x)
      (expected failure)

1 out of 17 tests failed (0.00s)
Test suite test: FAIL
```

Would you accept a change to the `Result` data type, to include the `OK` or `FAIL` string?

**Comment by feuerbach** [comment]
Oh cool. So it looks like you can make this a separate package, and the only change that needs to be done to tasty itself is this:

> Would you accept a change to the Result data type, to include the OK or FAIL string?

which I'm ok with.

**Comment by nomeata** [comment]
> So it looks like you can make this a separate package

I tried, but unfortunately not: `Test.Tasty.Core` is not exposed.

**Comment by feuerbach** [comment]
The idea there was indeed not to expose Core, but rather to expose parts of it through Providers and Runners. So if there's anything you need not exposed through those modules, we can certainly add that.

**Comment by nomeata** [comment]
> > Would you accept a change to the Result data type, to include the OK or FAIL string?
> which I'm ok with.
Added to the pull requestion.

About what to export where, and what functionality must be exiled to a different package, I’ll leave that to you: Merge the parts you like, and I’ll pick it up from there (if you really do not want to have that small functionality included with tasty.)

**Comment by nomeata** [comment]
Ah, I just now see that all the details of `TestTree` are indeed exported, in `Test.Tasty.Runners`. So yes, the newly added module could go into a separate package.

I still would prefer not having so many small packages to maintain and to keep in sync, and rather prefer `tasty` to provide this optional and lightweight functionality out of the box. Are you sure it is not something that could live in the core package?

**Comment by feuerbach** [comment]
Yes, that's the philosophy behind tasty: keep it reasonably minimalistic and let people extend it as they like. If this code can live outside of tasty, then it should.

This is better for you as well: you don't need to convince me that an addition is good and other people need it; you just go ahead and release your add-on and change it in the future without having to go through the central repo.

**Comment by feuerbach** [comment]
I merged resultShortDescription; unless something else comes up, I'll upload a new version soon.

**Comment by nomeata** [comment]
Ok, I wait for that release and package the `Wrap` module separately as `tasty-expected-failure`.

**Comment by feuerbach** [comment]
Released as tasty-0.11.

**Comment by nomeata** [comment]
Uploaded as http://hackage.haskell.org/package/tasty-expected-failure

**Comment by boggle** [comment]
I find it strange that this was not moved into tasty core - this is a pretty common technique, many other test frameworks include something like this by default (e.g. @Ignore in JUnit) to support the test first workflow described above.

**Comment by pheaver** [comment]
This feature was difficult to find because it's part of a separate package.

**Comment by saurabhnanda** [comment]
I just started using tasty, managed to write two tests, and the third test was supposed to be a known failure. I wasn't able to find this feature in the core library. Please reconsider your decision and add the ability to mark known failure or skip certain tests.

**Comment by feuerbach** [comment]
> I wasn't able to find this feature in the core library.

Yes, but you were able to find it in the non-core library, weren't you?

It doesn't mean much that it's not in the core library. The fact that you managed to write any tests at all means that you already used a non-core library (such as tasty-hunit).

If it was difficult to find, how did you search for it?

Joachim's package is literally the first google hit here (in a fresh incognito window):

![tasty-expected-failure](https://user-images.githubusercontent.com/24844/27075432-c427eebe-5032-11e7-81f2-fc48fd78a364.png)

It is also listed in the README.

What else can be done to make it more discoverable?

**Comment by saurabhnanda** [comment]
@feuerbach please do not get antagonised by my comment. My intention was not to attack you in any way. My POV is that this seems like a core feature that should not be split out into a separate package. I generally err on the side of bundling things, to deliver a better "programmer UX"

**Comment by saurabhnanda** [comment]
And FYI, here is a comment I added to QuickCheck with a similar intention -- https://github.com/nick8325/quickcheck/issues/80#issuecomment-307888563 & https://github.com/nick8325/quickcheck/issues/80#issuecomment-308020031

**Comment by feuerbach** [comment]
> My POV is that this seems like a core feature that should not be split out into a separate package

Yes, I get it. But I haven't heard any convincing arguments in support of that POV.

**Comment by boggle** [comment]
@feuerbach if this thread doesn't convince you, I don't know what will. People going out of their way to tell you that their experience as a user is bad (which is great,it means we love your software in general, otherwise we wouldn't bother and just move on) because of an insistence on architectural purity should be a red flag for any one designing a public api for consumption by others.

**Comment by feuerbach** [comment]
This is not just about architectural purity. This is also about saving my time. I have 50+ open PRs and issues across my open source projects that need some work for me, and [I haven't managed to get much help with them](https://ro-che.info/articles/2017-05-04-help-haskell-open-source).

So if I can have someone else implement and support a feature, I'd rather go that route.

**Comment by pheaver** [comment]
@boggle I agree with you that it's inconvenient for the users, however it's comments like this that make me reluctant to take up any major OSS projects, because you guys are incapable of seeing the developer's point of view. You literally think that your inconvenience should be the only factor, or at least you are arguing that way. Sorry if that sounds harsh, but I think it should be said.

**Comment by sshine** [comment]
Just for the reference, I was looking for this feature in the Tasty and Hspec docs a couple of weeks ago and didn't find them until I incidentally bumped into the `tasty-expected-failure` package googling for [something else entirely](https://www.google.com/search?q=haskell+tasty+report+number+of+passed+tests+ci|"continuous+integration") (which, due to Google's algorithms, might not show `tasty-expected-failure` in your results, though).

So for me, having had this as a core feature I'd have found it sooner.

As for the logistics of being an emcumbered package maintainer, I have nothing wise to say.

**Comment by massysett** [comment]
@feuerbach I agree with you 100%.  It's fine if you think your inconvenience should be the only factor, seeing as the people who think otherwise are not paying your bills.

**Comment by emilypi** [comment]
I'd like this to be a core feature, because this an integral component to many production tests. @feuerbach if you'd like help with this, let's talk. You know how to reach me, and Iid be happy to do it.

**Comment by lorenzo** [comment]
It would be really nice to have this in the core :)

**Comment by Ericson2314** [comment]
I too have ended up here. Seems like on the grounds of content vs presentation, even, it might be better in the core.
