### ISSUE TITLE
Test runner hanging

### ISSUE THREAD

**Issue by mitchellwrosen** [feuerbach/tasty#116]
I haven't managed to put together a simple example, but a test suite I've written seems to be hanging before printing output. I can Ctrl+C one time, and then I see the final results (all tests are passing). The "OK (time)" shows the time the entire run takes, including hang time, so it's not the case that stdout needs to be flushed, or something like that.

To give you at least _some_ context, this seems to happen when my test includes an FFI call that calls poll, but I don't know how that's related. Sorry for the vague-ish bug report. Any idea what might be happening?

**Comment by feuerbach** [comment]
No, I'm afraid this is too little info. I hope you can come up with a reproducible example.

**Comment by mitchellwrosen** [comment]
Apologies, this line from the `async` documentation is what's biting me:

```
In particular, if the target thread is making a foreign call, the exception will not be thrown until the foreign call returns, and in this case cancel may block indefinitely.
```

Tasty's all well and good!
