### ISSUE TITLE
Running tests sequentially with -threaded

### ISSUE THREAD

**Issue by mitchellwrosen** [feuerbach/tasty#117]
Hi,

I have some tests that need to run sequentially (because they are binding sockets to the same port and such), but each test itself needs to be run with the multithreaded runtime. Is there a way to accomplish this with `tasty`? The only thing I found is wrapping the top-level `TestTree` with `localOption (NumThreads 1)`, but this of course doesn't work because each individual test needs more than 1 thread.

Thanks,
Mitchell

**Comment by feuerbach** [comment]
tasty uses the number of capabilities only as a default value for the number of parallel jobs. You can control the number of jobs directly using the `-j` flag or the equivalent environment variable.

**Comment by mitchellwrosen** [comment]
What's a "job"? A single `TestTree`?

**Comment by mitchellwrosen** [comment]
Ah, I see what you mean, `-j` controls the number of threads that are running tests, which does not affect how many threads the tests may spawn. Thanks a lot! Closing the issue.
