### ISSUE TITLE
`--quickcheck-show-replay` shouldn't require `True` as an argument

### ISSUE THREAD

**Issue by sjakobi** [feuerbach/tasty#120]
Currently one has to write e.g. `./test --quickcheck-show-replay True` to activate the option whereas `./test --quickcheck-show-replay` wouldn't be any less clear.

**Comment by sjakobi** [comment]
I've been looking into how to make the argument optional, such that `./test --quickcheck-show-replay True` and `./test --quickcheck-show-replay` would have the same effect, and `./test --quickcheck-show-replay False` and `./test`. I think that would be nice for backwards compatibility.

I believe that https://github.com/pcapriotti/optparse-applicative/issues/53 contains some related information.

**Comment by HuwCampbell** [comment]
Not sure if that issue is related. https://github.com/pcapriotti/optparse-applicative/issues/148 offers a few ways to do something pretty reasonable though.
`--quickcheck-show-replay` vs. `--quickcheck-show-replay-off` are pretty easy for instance.

**Comment by feuerbach** [comment]
I made it a simple flag (in a non-backwards-compatible way, but I don't think this will negatively affect many people).

I actually figured out how to do what you wanted (and also #121) with GetOpt (see the `getopt` branch), but I hesitate to release that version because it's a major breakage.

**Comment by sjakobi** [comment]
Thanks a lot! 👍
