### ISSUE TITLE
Fail-fast feature

### ISSUE THREAD

**Issue by MichaelXavier** [feuerbach/tasty#124]
One feature I find myself missing from hspec is the --fail-fast flag, which will end the test run on the first failure. This is useful if you have tons of tests failing and you just want to iteratively step through them and solve them. Is this a feature you'd be interested in for tasty? I'd be open to implementing it myself. Do you think it would be fairly straightforward to do so? I haven't familiarized myself with tasty's internals yet.

**Comment by feuerbach** [comment]
This should be straightforward to implement as a standalone test reporter, so it could be a third-party package maintained by you.

The standard console reporter (`core/Test/Tasty/Ingredients/ConsoleReporter.hs`) does something very similar for `--quiet`; it stops on the first failure (but does not produce any output). So you could start from there.

Given that we already have a similar feature, I *could* accept yours in `ConsoleReporter`, but:

* you'll need to integrate it in such a way that will make it even simpler than it is right now, or at least no more complex (and then convinve me that it really is). It is possible but not easy. I've spent considerable time to make that module implement several modes of operations while keeping its complexity manageable.
* I'm not fast to merge pull requests nowadays.

So it'd certainly be easier for you to implement it as a separate package.

**Comment by MichaelXavier** [comment]
@feuerbach Thanks for the guidance. Given your suggestions, I would probably go with your suggestion of making my own package. The problem I see however is that my functionality does not aspire to be a test output formatter. For instance, for fun a while ago I made a test formatter that outputs in TAP format. Ideally I'd like the user to be able to choose that formatter instead of the default but add the ability to "fail fast". I'm not sure if this is possible to do as a library with the tools available. An ingredient would need a way to act as a pass-through.

**Comment by feuerbach** [comment]
I think that's kinda possible too, if you structure your component as a function `Ingredient -> Ingredient`. That function could pass a different StatusMap downstream, and after the first failure, it would fill up the remaining TVars with something, forcing the downstream formatter to finish.

**Comment by MichaelXavier** [comment]
Brilliant! That makes sense to me. Thank you!

**Comment by MichaelXavier** [comment]
Done! https://hackage.haskell.org/package/tasty-fail-fast
