### ISSUE TITLE
Tasty Discoverer

### ISSUE THREAD

**Issue by taylor1791** [feuerbach/tasty#127]
Does Tasty have a Discoverer like [HSpec](http://hspec.github.io/hspec-discover.html)? If not, how much of a priority is this?

**Comment by feuerbach** [comment]
Well there's this https://hackage.haskell.org/package/tasty-th-0.1.3/docs/Test-Tasty-TH.html

Personally I don't use either of them, so I don't know how similar or different they are.

> If not, how much of a priority is this? 

As much as you are willing to assign to it :) Tasty's philosophy is that if it doesn't need to be part of the core package, it shouldn't. So feel free to write a package that would do what you want and publish it on hackage.

**Comment by lwm** [comment]
@taylor1791 - any movement on this? Once I get some free time, I think this would be worth looking into. Hspec is of course a good source of inspiration ...

**Comment by taylor1791** [comment]
@lwm I havn't spent any additional time on it. I will probably have some time in early march to look at it. If you want to do it, don't let me stop you. Looking at the Hspec discover makes it appear to almost be a copy and paste job.

**Comment by lwm** [comment]
@taylor1791 - I've added my first iteration on a test discoverer. It currently only supports hunit and quickcheck properties but it can quickly catch up with hspec and others (if they are under the umbrella of Tasty). Raise any issues or feel free to hack on it!

https://github.com/lwm/tasty-discover
