### ISSUE TITLE
Way to mark tests as failing

### ISSUE THREAD

**Issue by ezyang** [feuerbach/tasty#128]
When bugs happen, it's useful to immediately check in a failing test case (to be fixed at some later point.) It would be nice if I could have HUnit mark it as "failing", and let us know if it unexpectedly passes at some later point in time.

**Comment by feuerbach** [comment]
@nomeata did just that recently, see https://hackage.haskell.org/package/tasty-expected-failure

**Comment by nomeata** [comment]
@ezyang, we are spoiled by working on GHC, aren’t we? :-) (Also see #114 for context.)

**Comment by ezyang** [comment]
OK, thanks!

**Comment by ezyang** [comment]
That's a funny rant you have on the page. I'm confused by the "minimal experience", because Tasty definitely does not have very minimal dependencies ^^

**Comment by feuerbach** [comment]
No? I think tasty has a reasonably small set of (transitive) dependencies by modern standards.

But that's not what I meant. It is minimalistic in terms of features/code, so that it is easy for me to maintain and for you to extend without depending on me agreeing with you.
