### ISSUE TITLE
Add source locations

### ISSUE THREAD

**Issue by bergmark** [feuerbach/tasty#131]
For example: HUnit added source locations to errors in august but this has never made it into tasty because tasty-hunit was duplicated from HUnit. Does it still make sense to have this separation?

**Comment by feuerbach** [comment]
I haven't yet looked into source locations. Are they in ghc 7.8?

**Comment by bergmark** [comment]
No it's ghc >= 7.10 only, HUnit adds them conditionally https://github.com/hspec/HUnit/blob/master/Test/HUnit/Base.hs#L46

**Comment by feuerbach** [comment]
Yeah, I actually meant 7.10, have a hard time remembering what the last release is.

I think it's a cool feature, it'd be great if someone added support for it to tasty.

Here's how I see it:

* the (optional) location would be a part of the test's result (need to think where to fit it in)
* test providers (including tasty-hunit) would fill it in
* test reporters could display it in a special way (e.g. with a different color on the console)
* there should be a (test-level) option to suppress them, like when the tests are generated based on files, and the source location doesn't identify a test

**Comment by lippling** [comment]
+1

**Comment by feuerbach** [comment]
tasty-hunit shows source locations since version 0.10; closing.
