### ISSUE TITLE
Missing support for GHC 8

### ISSUE THREAD

**Issue by asr** [feuerbach/tasty#132]
I couldn't install the library using GHC 8.0.1 RC1.

**Comment by feuerbach** [comment]
Could you be more specific? What was the problem?

**Comment by asr** [comment]
After testing the dependencies, the problem is related to optparse-applicative  which doesn't support GHC 8 (see https://github.com/pcapriotti/optparse-applicative/issues/183).

**Comment by feuerbach** [comment]
That's right. You can work around that by passing `--allow-newer` to cabal install.
