### ISSUE TITLE
User question: print some logging information on failure

### ISSUE THREAD

**Issue by ezyang** [feuerbach/tasty#135]
Is there a way to run some extra command when a test fails? In particular, on all tests I write out a log file and when the test fails I'd like to print the contents of the log to the user (since in CI environments I can't easily get to the log in question.)

**Comment by feuerbach** [comment]
I assume you're asking about HUnit tests.

I would do something like

``` haskell
import Test.Tasty
import Test.Tasty.HUnit
import System.Process (readProcess)
import Control.Exception (handle, throwIO)

main = defaultMain $ testCase "Failing case" . printLogs $ assertFailure "Bam!"

printLogs = handle $ \(HUnitFailure msg) -> do
  logs <- readProcess "journalctl" ["-n", "5"] ""
  throwIO $ HUnitFailure (msg ++ "\n" ++ logs)
```

**Comment by ezyang** [comment]
Great, thank you!
