### ISSUE TITLE
defaultMain and friends should return rather than assuming flow control

### ISSUE THREAD

**Issue by jtdaugherty** [feuerbach/tasty#136]
The `defaultMain` and `defaultMainWithIngredients` functions currently assume flow control and call exit functions after the test suite has run.  I find this to be surprising behavior because it means my only recourse for doing anything after the test suite is to use `Control.Exception` (i.e. `catch` or `finally`).  Although it is nice to know that a failing test suite will guarantee a nonzero exit status, it would also be nice to not have to resort to exception handling to regain control from the test suite.

Would you be open to considering alternatives?

One such alternative would be to make it so that `defaultMain` and friends return a `Bool` indicating whether the test suite passed and let the calling environment deal with it.  In addition to being less surprising (to me), this has the benefit that it lets Tasty put off the decision about how to deal with the test suite failure; for some programs exiting might be the right thing to do, but for others it really might not!

Another approach would be to leave the functions as they are and add new entry points that are designed to provide this kind of control.  That approach would work but it wouldn't make for composable `main` alternatives.  Still, I imagine it would be nice to keep churn to a minimum to avoid disrupting existing users' environments.

(CC @tommd)

**Comment by feuerbach** [comment]
The defaultMain provides the right default. You almost always want the exit status of your test suite indicate whether it passed.

As you note, the behavior you want is just a `catch` away -- so I don't see a compelling reason to add or change anything.

**Comment by jtdaugherty** [comment]
To summarize, then: since I want neither of the behaviors you mentioned, either my original request was not clear or we are in disagreement about this. Can you clarify?

**Comment by feuerbach** [comment]
Not sure what you mean by "neither of the behaviors". I thought we only discussed the behavior of tasty calling `exitWith`.

> I find this to be surprising behavior because it means my only recourse for doing anything after the test suite is to use Control.Exception (i.e. catch or finally).

To be sure, the fact this behavior is surprising is bad. In that case it should be documented somewhere.

I can also see how, in your use case, you wish `defaultMain` behaved differently. Yet the majority of users simply set `main = defaultMain` and expect it to do the right thing (which it does).

The alternative -- adding variants that return a `Bool` -- makes me maintain twice as many `defaultMain` functions, which I am also reluctant to accept, especially given that the desired behavior can be easily implemented on top of what is provided.

> it would also be nice to not have to resort to exception handling to regain control from the test suite

I can sympathize with this; however, nice is not free, as I tried to explain above. This is similar to the compromise made in `System.IO`: if you want `openFile` to return `Nothing` when a file does not exit, you would not like its semantics; but most people *do* want it to throw an exception, and for the cases like yours, there are exception-handling facilities.

**Comment by jtdaugherty** [comment]
By "neither of the behaviors" I was referring to the two statements in your response: "You almost always want the exit status of your test suite indicate whether it passed" (yes, I do almost always want that but not before getting a chance to do other things) and "the behavior you want is just a catch away" (I think use of `catch` is a hack in this case).

To reiterate, we are in agreement that having `defaultMain` do what it does right now is "the right thing to do" for many use cases, so I wouldn't recommend getting rid of it.  I also acknowledged in my original request that maintaining `main` variants that return `Bool` would be unpleasant, too, so we are in agreement on that.

I'm not going to get into a more general argument about exceptions here.  In this particular situation I don't think "just catch the exception" is a satisfactory response.  I agree that it's okay for the default main functions to do this automatically *only* if there is an alternative API that provides more control.  What I am hearing is that you are not open to adding such an API *in addition to* what is already there.  Can you confirm?

**Comment by feuerbach** [comment]
Yep.

**Comment by dagit** [comment]
I was just bitten by this odd design choice.

**Comment by hsenag** [comment]
I also find this inconvenient (having to catch exceptions).
