### ISSUE TITLE
type TestName = Text

### ISSUE THREAD

**Issue by mitchellwrosen** [feuerbach/tasty#140]
Would it be reasonable to replace

``` haskell
type TestName = String
```

with

``` haskell
type TestName = Text
```

in an effort to abolish `String` wherever possible from commonly used libraries?

**Comment by feuerbach** [comment]
There's nothing impossible here, but let's look at pros and cons.

Cons:
* Almost every existing test suite will break
* Users need to put an extra line of boilerplate (enable overloaded strings)
* Extra dependency (this is a minor one)

Pros:
* People will not be irritated by seeing `String`s in type signatures?
