### ISSUE TITLE
--quickcheck-show-replay True does not work 

### ISSUE THREAD

**Issue by NovaDenizen** [feuerbach/tasty#141]
When I include `--quickcheck-show-replay True` in the command line of a test program I expect it to print seeds for all tests, successful and failed.  Unfortunately, this does not seem possible since `Test.QuickCheck.Test.Result`'s `Success` constructor does not make the seed available as one of its fields. 

It could be made to work if tasty-quickcheck used `Test.QuickCheck.Random.mkQCGen :: Int -> QCGen` to specify all seeds passed to QuickCheck instead of allowing it to generate its own.  I'm working on a patch that does this.

**Comment by NovaDenizen** [comment]
Ok, I have a patch that works.  

QuickCheck, in it's `Failure` record of type 'Result', returns the `QCGen` and int size used for the failing test, not the QCGen used to seed the start of each test series.  QuickCheck uses an irritatingly quirky mechanism (`computesize'` in Test/QuickCheck/Test.hs) to pick the size of each individual test.

QuickCheck apparently intends for a user to take the `usedSeed` and `usedSize` from the `Failure` record and stick them into the`(QCGen, Int)` pair passed in as the `replay` field of `Args`.  This results in the first test case generated will then exactly match the test case that previously failed.  The tests that come after will be entirely different thanks to different test sizes being used.

My patch generates an int seed (from `getStdRandom`) for each test run on a property, unless an int seed is passed in via the `--quickcheck-replay` flag.  So the replay field in `Args` is always of the form `Just (mkQCGen seed, 0)`.  The 0 makes QuickCheck start with a test case of size 0, the same way it would as if `Nothing` were passed in on `replay`.  So when a seed is specified, all test cases that ran before will be run again.

As another bug, the default for `--quickplay-show-replay` was `True`, which seems wrong.  It was likely never seen as a problem because of the bug this patch fixes.  I set it to `False`.

**Comment by NovaDenizen** [comment]
Created a pull request https://github.com/feuerbach/tasty/pull/142

**Comment by NovaDenizen** [comment]
Whoops, I forgot to include my change to tasty-quickcheck.cabal, adding `random` as a dependency.

**Comment by feuerbach** [comment]
> When I include --quickcheck-show-replay True in the command line of a test program I expect it to print seeds for all tests, successful and failed.

I think this is not what most users expect. The idea is that you only care about the seed when the test fails, so that you can reproduce the problematic case. If tests pass, most users wouldn't care about the seed. This is also the reason why the option is True by default.

Why do you need the seed for passing tests?

**Comment by NovaDenizen** [comment]
I ran some quickcheck tests that took a surprisingly long time, so I wanted to use them with a fixed seed as a quick and dirty benchmark.  So I passed in `--quickcheck-show-replay True` and to my dismay no seeds were printed.  I wondered why, started looking into tasty-quickcheck and quickcheck, had a slightly clever idea about how to use `mkQCGen` to work around things, and now I'm here.

It seems like the option would be better named `--quickcheck-show-replay-on-error`.  I can't see a use for anyone ever passing `False` to it.  When there's an error you typically want to reproduce it, and unconditionally including the seed used in the test output does not present any conceivable kind of inconvenience to the user.

Another benefit of this patch is that it uses `Int`s as seeds instead of the nontrivial size/`TFGen` pair. so they are easiser to deal with and easier to make up one without needing to see one printed.  This part might be worthwhile to include, even if you choose not to include my changes to the logic deciding when to show seeds.

**Comment by feuerbach** [comment]
Your reasoning makes sense. I am now for changing the meaning of `--quickcheck-show-replay` as you describe.

> Another benefit of this patch is that it uses Ints as seeds instead of the nontrivial size/TFGen pair.

That is actually unsettling. TFGen is an improvement over Ints, and I wouldn't want to give it up.

Maybe you could plead your case to QuickCheck devs and have them make the necessary changes?

**Comment by sol** [comment]
>> Another benefit of this patch is that it uses Ints as seeds instead of the nontrivial size/TFGen pair.
>
> That is actually unsettling. TFGen is an improvement over Ints, and I wouldn't want to give it up.

Could you elaborate what you are worried about?  [`hspec`](https://hspec.github.io/) has been doing this for years?

**Comment by feuerbach** [comment]
Yeah, I was confused about that — I thought using random means no longer using tf-random inside quickcheck itself, but now I see it's not true.

So, if I understand correctly, there are two options: use an integer seed and convert it to QCGen (mkQCGen), or generate a QCGen from the beginning (newQCGen). This affects the way the user provides the replay seed.

Are you saying that hspec is using mkQCGen and not newQCGen? Is there a strong benefit to doing that?

I still lean towards newQCGen, it just seems more straightforward to me.

**Comment by sol** [comment]
> So, if I understand correctly, there are two options: use an integer seed and convert it to QCGen (mkQCGen), or generate a QCGen from the beginning (newQCGen). This affects the way the user provides the replay seed.

Yes, exactly, I think this are the two options you have.

> Are you saying that hspec is using mkQCGen and not newQCGen? Is there a strong benefit to doing that?

Yes, `hspec` uses integers as seed at the user interface.  The reason for this is that integers are subjectively nicer to deal with as a user + I don't know of any big disadvantage in doing so.

**Comment by feuerbach** [comment]
Cool, thanks a lot Simon.
