### ISSUE TITLE
tasty-quickcheck doesn't follow PVP

### ISSUE THREAD

**Issue by phadej** [feuerbach/tasty#144]
`Test.Tasty.QuickCheck` re-exports `Test.QuickCheck`. `QuickCheck-2.9` has a breaking change visible in `Test.QuickCheck`. 

Released versions of `tasty-quickcheck` should have `QuickCheck <2.9` bound. To support `QuickCheck-2.9` you'd need to make a major bump for `tasty-quickcheck`.

Re-exporting modules in convenient, but it would be easier not-to, if you aren't planning to provide consistent API (and follow PVP). And with change in the typeclass definition, you actually cannot.

https://github.com/haskell-infra/hackage-trustees/issues/71

**Comment by feuerbach** [comment]
> tasty-quickcheck doesn't follow PVP

if you are referring to the absence of an upper bound, that is by intention. I realize that it may occasionally cause problems; I'm sorry about that.

I don't have time to dig into what broke what this time around. If you describe the particular problem to me, maybe we can find a solution (or maybe not).

**Comment by phadej** [comment]
I'd suggest to make `tasty-quickcheck-0.9` which doesn't re-export `Test.QuickCheck`. Then you don't need to dig into `QuickCheck` changes, as long as API you (not users of `tasty-quickcheck`) use stays the same.

The ultimate goal is that validity of install plan for a package is determined exactly by its direct dependencies. It might be that some depend on `QuickCheck` only to control the API available thru `tasty-quickcheck`, which seems controversial to me.

**Comment by feuerbach** [comment]
You still haven't described the problem. What is the breaking change in QuickCheck and how did it affect you?

**Comment by phadej** [comment]
I depend only on `tasty-quickcheck` and used `exhaustive`. I adhere to PVP, i.e. specify bounds. Yet my package started suddenly breaking. Now I need to add `QuickCheck` dependency, even I don't use it directly to either
- be able to use `MIN_VERSION_QuickCheck` to align to the change of API of `QuickCheck`
- or to restrict `QuickCheck` bounds.

As user of package on Hackage, I expect that their visible API *does not change*, especially when my direct dependencies stays at exact same version. I have no resources to track transitive dependencies. I think, depending on them is semantically incorrect.

**Comment by feuerbach** [comment]
Ok, now you mention something about `exhaustive`. But you still haven't described the problem. What is the breaking change in QuickCheck and how did it affect you?

**Comment by phadej** [comment]
`QuickCheck-2.9` changelog says:

```
Remove "exhaustive" from Testable typeclass;
	  instead, combinators which are nonexhaustive (such as forAll)
	  call "again", which should be more robust
```

`Testable` is re-exported from `Test.Tasty.QuickCheck`, so its actual exports vary depending which version of `QuickCheck` solver picks. I'd like `tasty-quickcheck` provide consistent API, across different `QuickCheck`s, or not re-export the `Test.QuickCheck` at all.

**Comment by feuerbach** [comment]
If Test.Tasty.QuickCheck didn't export Testable, it would significantly reduce its convenience. test-quickcheck also doesn't attempt to abstract over QuickCheck.

If you want reproducibility, use stackage snapshots or cabal freeze. I don't think I can help you in this case.
