### ISSUE TITLE
quickCheck fails incorrect test that tasty lets through

### ISSUE THREAD

**Issue by joncol** [feuerbach/tasty#151]
I'm trying to solve a problem from the HPFFP book, but I've run into problems using tasty-quickcheck.

When running the test without Tasty, it fails as it should, but when running it using Tasty (tasty-quickcheck), it strangely passes. (I'm trying to show that a monoid instance is incorrect, due to wrong identity element.)

``` haskell
-- First, the one that works (test fails, as it should).

import Data.Semigroup
import Test.QuickCheck

data BoolConj = BoolConj Bool deriving (Eq, Show)

instance Semigroup BoolConj where
  BoolConj True <> BoolConj True = BoolConj True
  BoolConj _    <> BoolConj _    = BoolConj False

instance Monoid BoolConj where
    mempty  = BoolConj False -- <- note the error, should be BoolConj True
    mappend = (<>)

instance Arbitrary BoolConj where
  arbitrary = BoolConj <$> arbitrary

type IdType a = a -> Bool

rightId :: (Monoid a, Eq a) => a -> Bool
rightId x = x `mappend` mempty == x

main :: IO ()
main = quickCheck (rightId :: IdType BoolConj) -- OK, this works (i.e. test fails)


-- Then, the WRONG one
-- For some reason, when using Tasty to run the tests, the test incorrectly passes!?

import Data.Semigroup
import Test.Tasty
import Test.Tasty.QuickCheck hiding (Failure, Success)

-- Same instances and helpers as above.

main :: IO ()
main = defaultMain $ testGroup "Quickcheck tests"
  [ testProperty "BoolConj monoid has right identity"
      (rightId :: IdType BoolConj)
  ]
```

Am I doing something wrong?

**Comment by joncol** [comment]
OK, I must be doing something wrong here. When running everything from a single file, it works as it should. Please close this issue.

**Comment by joncol** [comment]
OK, it seemed to be because of orphan instance of Arbitrary typeclass. I had that in my test file. They should always be in the file of the data type?

**Comment by feuerbach** [comment]
Orphan instances are fine, just make sure you import the module where they are defined. (So if an instance is defined in your `test.hs`, it should be fine.)

**Comment by joncol** [comment]
OK, it seems that stack doesn't rebuild my tests correctly. I filed this: https://github.com/commercialhaskell/stack/issues/2724. I get the same problem whether I'm using QuickCheck or tasty-quickcheck.
