### ISSUE TITLE
Compose TestReporter ingredients

### ISSUE THREAD

**Issue by minad** [feuerbach/tasty#158]
In [tasty-stats](https://hackage.haskell.org/package/tasty-stats) I needed the possibility to compose two test reporters as shown below. It seems that only one reporter can be active, but I want console output and stats. I don't think this is an intended use of the API. Is there are better way to do that? Maybe it would be possible in a future version to distinguish between reporters and managers, allowing only one manager but multiple composable reporters?

~~~ haskell
composeReporters :: Ingredient -> Ingredient -> Ingredient
composeReporters (TestReporter o1 f1) (TestReporter o2 f2) =
  TestReporter (o1 ++ o2) $ \o t ->
  case (f1 o t, f2 o t) of
    (g1, Nothing) -> g1
    (Nothing, g2) -> g2
    (Just g1, Just g2) -> Just $ \s -> do
      h1 <- g1 s
      h2 <- g2 s
      pure $ \x -> h1 x >> h2 x
composeReporters _ _ = error "Only TestReporters can be composed"

statsReporter :: Ingredient
statsReporter = ...

consoleStatsReporter :: Ingredient
consoleStatsReporter = composeReporters consoleTestReporter statsReporter
~~~

**Comment by feuerbach** [comment]
> Maybe it would be possible in a future version to distinguish between reporters and managers, allowing only one manager but multiple composable reporters?

I think this makes sense, but some thought needs to be given to how to run the two reporters concurrently. Feel free to have a go at it.

**Comment by minad** [comment]
Ok, maybe I think about this problem when I have time. For now the `composeReporters` functions from above does it for me, but only allows sequential reporter execution.
I am not sure if there is a perfect solution which keeps the API compatible. Maybe this is more an issue to keep in mind if at some point you want to redesign the Ingredient type.

**Comment by feuerbach** [comment]
Why does API compatibility need to be broken?

**Comment by minad** [comment]
In the simplest case one could just add this utility function which also supports parallel execution of the reporters:

~~~ haskell
composeReporters :: Ingredient -> Ingredient -> Ingredient
composeReporters (TestReporter o1 f1) (TestReporter o2 f2) =
  TestReporter (o1 ++ o2) $ \o t ->
  case (f1 o t, f2 o t) of
    (g1, Nothing) -> g1
    (Nothing, g2) -> g2
    (Just g1, Just g2) -> Just $ \s -> do
      h1 <- async $ g1 s
      h2 <- async $ g2 s
      (i1, i2) <- waitBoth h1 h2
      pure $ \x -> do
        j1 <- async $ i1 x
        j2 <- async $ i2 x
        fst <$> waitBoth j1 j2
composeReporters _ _ = error "Only TestReporters can be composed"
~~~

Would you like that as a PR or should this be just kept in a separate lib?

There is no real need to break API compatibility if you are happy with such a function. However I see it as follows - the function being partial indicates that I am doing something not really intended and that I work against the types. But at the same time I don't want to overthrow your API or break backward compatibility for no good reason.

**Comment by minad** [comment]
Oh, I've just seen this could use the concurrently function instead. Just let me know what you think.

**Comment by feuerbach** [comment]
Yes, this looks reasonable — and I agree about simplifying this with `concurrently`. If you want to get it in, I'm happy to accept a pull request.

I don't see much harm in a partial function here as long as it's clearly marked as such.

**Comment by minad** [comment]
Ok, cool!
