### ISSUE TITLE
Threaded runtime but sequential test execution should be possible

### ISSUE THREAD

**Issue by osa1** [feuerbach/tasty#161]
Threaded runtime implies concurrently running the tests, but that's not always ideal. Sometimes I want to run my tests using threaded runtime and with `-N`, but run the whole test suite sequentially (i.e. tests shouldn't overlap). Currently tasty doesn't provide a way to do this and this would be a great addition.

**Comment by feuerbach** [comment]
You can set the number of tasty threads to 1 on the command line. ghc's `-N` is only used as a default.

**Comment by osa1** [comment]
Thanks, I didn't know that, and that's great. My next question is how do I set that parameter in runtime, using `tasty` API.

Passing argument to test programs is just too painful these days, because we rarely directly run test programs, usually `stack`, `cabal`, `nix` etc. run them. So usually I end up using environment variables instead of command line arguments. In this case though I don't think tasty provides a function to set that parameter, or at least I can't find it in the documentation. Any help?

Thanks again.

**Comment by feuerbach** [comment]
You can set the environment variable from your test program (using `setEnv`) before calling `defaultMain`.

**Comment by osa1** [comment]
> the environment variable

what env variable? Does tasty check an environment variable for setting `-j`?

**Comment by feuerbach** [comment]
Yes, the full name for that option is `--num-threads`, hence the environment variable is `TASTY_NUM_THREADS`.

**Comment by osa1** [comment]
Awesome! Thanks a bunch.

**Comment by feuerbach** [comment]
I also added more info about this to the readme.
