### ISSUE TITLE
Patterns don't work when they include slashes

### ISSUE THREAD

**Issue by minad** [feuerbach/tasty#164]
Hi @feuerbach,

I am using golden tests where the test names are derived from filenames with slashes in it. If I use `--pattern *Gold*/*partoffilename*` and the filename contains slashes it doesn't select the tests. The reason is probably that tasty uses slashes for the testtree levels? Is there a workaround?

**Comment by feuerbach** [comment]
Yeah — I haven't tried it myself, but I am not surprised that it doesn't work... and no, I don't know of any workarounds, though they may exist.

Unfortunately, I don't have time to look into it. So your options might be to:

1. hack something around the pattern matching code — I may be open to merging it if it's not too gross
2. If you are interested in working on a [richer pattern language](https://github.com/feuerbach/tasty/issues/38), that would be even better.

**Comment by minad** [comment]
Ok, thx for your answer. I might fix this at some point. I also just saw that you already mentioned this problem in #38.

**Comment by minad** [comment]
thank you! awk patterns are great :)
