### ISSUE TITLE
Unable to set the `UseColor` option for individual TestTrees

### ISSUE THREAD

**Issue by kRITZCREEK** [feuerbach/tasty#165]
Hello everyone :) I was wondering if it's possible to set the `--color` flag only for certain parts of the TestTree. 

My particular use-case is moving the `purescript` test suite to tasty in https://github.com/purescript/purescript/pull/2848, but I'm running into exceptions on Windows: `getConsoleCursorInfo: invalid argument (Invalid handle.)`. These seem to happen because both the PureScript compiler, which gets run in the tests, as well as tasty attempt to control the terminal's color output and conflict with one another. 

I can make the test suite run succesfully by passing the `--color=never` option, but I'd rather only turn it off on the test tree that runs the compiler, and only if it's run on windows and not explicitly set.

When reading the source code, it seems that it's currently impossible because `UseColor` is not exposed from https://github.com/feuerbach/tasty/blob/2b53e20108312ff0a97e764c99a049df028ef3a4/core/Test/Tasty/Ingredients/ConsoleReporter.hs#L350-L352

Would a PR that exposes it be accepted?

**Comment by feuerbach** [comment]
> Would a PR that exposes it be accepted?

If this is all it takes — absolutely.

**Comment by kRITZCREEK** [comment]
I had a go at this yesterday and it seems your skepticism...

> If this is all it takes — absolutely.

...was totally justified 😞 I'll investigate further on how to fix my problem, but I doubt the solution will be to turn off colors for individual test trees, so I'll close this issue.
