### ISSUE TITLE
Disable test-suite using presence of test pattern

### ISSUE THREAD

**Issue by kanishka-azimi** [feuerbach/tasty#169]
https://github.com/LeventErkok/sbv/pull/277/files - in case this is of interest to you, or you want to implement some convenience functions to make this simpler.

I was trying to avoid cabal flags and buildable, because I think cabal flag values are used in deciding whether to rebuild a library.

Feel free to close or address as you wish.

**Comment by feuerbach** [comment]
I suppose one way I could help you is by adding an Eq instance for patterns?

**Comment by kanishka-azimi** [comment]
Whatever fits within your vision for this library. My use case might be a hack or might be useful to others. I often find myself wanting to create the combination of a library, an exe, a unit test suite, and an integration test suite, with the integration test suite compiled but not run by default, so that a release can run `cabal test` or `stack test` without a problem.

As noted in the PR text, I also ran into either undocumented or unexpected behavior with respect to trying to override the testpattern option (I wanted to set the pattern to '!**' conditionally.)

**Comment by kanishka-azimi** [comment]
Closing as I am not actively waiting to use this myself.
