### ISSUE TITLE
Request for code sample: Using tasty with a DB connection pool

### ISSUE THREAD

**Issue by saurabhnanda** [feuerbach/tasty#170]
I spent some time looking around for an example that shows how to use `withResource` to run tests using a common DB connection pool; where every test is run in a separate transaction and the transaction is always rolled-back at the end of the test.

If you can help me with the simpler version of the code -- just running tests with access to a DB connection pool, I should be able to figure out the transaction bit.

**Comment by feuerbach** [comment]
Sorry, I can't offer this kind of support. Try asking on stackoverflow, and be sure to mention what you already tried and what presents a problem for you.
