### ISSUE TITLE
Parallel tests with a DB connection pool

### ISSUE THREAD

**Issue by saurabhnanda** [feuerbach/tasty#171]
I'm stuck with adding a QC property to a `TestTree` where a connection is taken from a DB pool and passed to the property. I **believe** (please correct my, if I'm wrong), that if I pass the same connection to every single test in the `TestTree` then they will not run in-parallel. However, if a new connection is taken from the `ConnectionPool` and passed to each test, then they will run in parallel with no problem.

```
import Test.Tasty.HUnit as H
import Test.Tasty.QuickCheck as QC
import Test.QuickCheck.Monadic as QCM
import Data.Pool as P

tests :: ConnectionPool -> TestTree
test dbPool = testGroup "All tests"
  [
    H.testCase "A single connection can be taken from the DB pool and passed to HUnit tests" $ P.withResource dbPool (\conn -> testThatRequiresDB conn)

    -- QUESTION: How do write the following line?
  , QC.testProperty "How do aI pass a connection to a QC property because obviously this won't typecheck!" $ P.withResource dbPool (\conn -> propThatRequiresDB conn)
  ]

-- NOTE: The following property can be run via the REPL, but it's not so simple to 
-- add it to my Tasty TestTree
--
-- > conn <- connectPostgreSQL "dbname=xxx user=xxx password=xxx"
-- > quickCheck (propThatRequiresDB conn)

propThatRequiresDB :: Connection -> MyDataWithArbitraryInstance -> Property
propThatRequiresDB conn arb = monadicIO $ do 
  -- test body comes here and can use `conn`
  QCM.assert (True)
```

**Comment by feuerbach** [comment]
Tasty will attempt to run the tests in parallel if `--num-threads` says so. In theory, you could reuse the same connection in multiple threads if your database and driver support that.

QuickCheck allows you to write monadic properties, see https://hackage.haskell.org/package/QuickCheck-2.10.0.1/docs/Test-QuickCheck-Monadic.html

**Comment by saurabhnanda** [comment]
>  In theory, you could reuse the same connection in multiple threads if your database and driver support that.

True, but I don't think sharing the same DB connection across threads would be a wide decision, in practice.

> QuickCheck allows you to write monadic properties, see https://hackage.haskell.org/package/QuickCheck-2.10.0.1/docs/Test-QuickCheck-Monadic.html

Yes, and I am using that to define `propThatRequiresDB` above. It's just that I don't think there is any way to put that test into a `TestTree` and hand it over a new connection every time it runs. Is there?

**Comment by feuerbach** [comment]
> True, but I don't think sharing the same DB connection across threads would be a wide decision, in practice.

There is no a priori reason to think that, it all depends on the db and driver.

> Yes, and I am using that to define propThatRequiresDB above. It's just that I don't think there is any way to put that test into a TestTree and hand it over a new connection every time it runs. Is there?

So I think your code can't typecheck because you invoke `P.withResource` outside of `monadicIO`. You should instead pass the pool to `propThatRequiresDB` and run `P.withResource` within `monadicIO`.

If you don't want to run `withResource` every time the property runs but instead reuse the same connection, use tasty's [`withResource`](https://hackage.haskell.org/package/tasty-0.11.2.1/docs/Test-Tasty.html#v:withResource) to grab a connection from the pool once and store it in an IORef.

**Comment by saurabhnanda** [comment]
> There is no a priori reason to think that, it all depends on the db and driver.

Let me flip the question around. What is the **recommended** to write a tasty test-suite, containing, both HUnit test cases and QC properties, with Postgres such that:

* Parallelism is used if compiled with `--num-threads`
* Tests don't interfere with each other when communicating with the DB

**Comment by saurabhnanda** [comment]
I'm trying to make this work `Test.Tasty.withResource` but I'm not sure how to get it done:

```
   QC.testProperty "using withResource" $ Test.Tasty.withResource 
      (return ()) -- no need to initialise the resource, dbPool is already initialised
      (return ()) -- no need to free the resource, dbPool will be freed at the end of the ENTIRE test-suite
      (Data.Pool.withResource dbPool (\conn -> -- WHAT DO DO HERE?)
```

**Comment by feuerbach** [comment]
As far as I know, postgres connections are not multiplex, so your approach looks correct to me.

When you use `Test.Tasty.withResource`, in the initialization action, extract the connection from the pool and put it into an IORef. In the finalization action, put the connection back into the pool.

If this is too complicated, abandon `Test.Tasty.withResource` and simply move `Data.Pool.withResource` inside `monadicIO`. This will be a little bit slower but probably unnoticable compared to the DB latency etc.
