### ISSUE TITLE
Tasty -> QuickCheck Args

### ISSUE THREAD

**Issue by mitchellwrosen** [feuerbach/tasty#172]
Hello!

Would it be possible to expose a function with the type

```haskell
Tasty.OptionSet -> QuickCheck.Args
```

in the `tasty-quickcheck` package? My use case is simply to keep `tasty-hspec` in sync with the behavior of `tasty-quickcheck` since `hspec` also accepts QuickCheck `Args`.

I think it would be surprising if, depending on which package you pass your tasty `OptionSet` to, the underlying QuickCheck args are actually set to one thing or another.

https://github.com/mitchellwrosen/tasty-hspec/pull/14

Thank you!

**Comment by feuerbach** [comment]
That makes sense. I'll try to do that in the next few days -- or feel free to send a pr (if you do, include the version bump and a change log entry).
