### ISSUE TITLE
Quiet mode exit-code is confusing

### ISSUE THREAD

**Issue by LeventErkok** [feuerbach/tasty#176]
Perhaps I'm just not using tasty correctly here, but the following confuses me. Consider:

```haskell
-- a.hs
module Main(main) where

import Test.Tasty
import Test.Tasty.HUnit

main = defaultMain tests

tests :: TestTree
tests = testCase "1" (1 @?= 1)
```

I have:

```
$ ghc -o a a.hs
[1 of 1] Compiling Main             ( a.hs, a.o )
Linking a ...
$ ./a
1: OK

All 1 tests passed (0.00s)
$ echo $?
0
$ ./a -q
$ echo $?
1
```

Note that the exit code is `0` when run normally (which is what I would expect), but it is `1` when run in quiet mode.

Why is the exit-code not `0` when run in quiet mode? (I'm doing this on a Mac, if that matters at all.)

**Comment by feuerbach** [comment]
That's definitely a bug.

**Comment by LeventErkok** [comment]
Thanks for the quick turnaround! Much appreciated!
