### ISSUE TITLE
Negated patters slow down tasty

### ISSUE THREAD

**Issue by LeventErkok** [feuerbach/tasty#177]
@feuerbach 

Note: This is most likely the same root cause as https://github.com/feuerbach/tasty/issues/175, but opening a new ticket here to draw attention to an actual use case that rather blocks me from deploying a tasty test-suite on travis.

I've a large test suite, that I'd not only like to run locally but also on travis. Tasty is great for that. Unfortunately, I cannot run every test on travis due to dependencies. I've marked such tests carefully with the name `noTravis_`. When I run locally, I use the command:

   `cabal test SBVTest`

And on Travis I use:

  `cabal test SBVTest --test-options=-p!noTravis_`

This works just fine, except the latter adds such an overhead that I cannot get the VM's available in Travis to actually complete the test within 30minutes; a rather unfortunate situation.

For reference, when I ran the above commands locally, I get:

  * 13m 55s for the first case
   * 18m 40s for the second case

So, it costs me 5 minutes more for fewer number of tests.

I understand you'll overhaul the entire pattern mechanism; but I'm curious if there might be a short-term fix in the mean-time that at least stops the recompilation of the regex over and over when given large number of tests. With that fix in place, I think the actual overhaul of patterns can wait till later.

Thanks!

**Comment by feuerbach** [comment]
I don't think it has anything to do with negation; the code for negation is rather trivial and shouldn't add any overhead. Besides, you are not comparing patterns with and without negation; you are comparing a pattern and no pattern. So this does seem the same as #175.

Anyway, I just pushed a commit to the master branch — could you try it and see if it improves the timing sufficiently?

**Comment by LeventErkok** [comment]
@feuerbach 

Yes, much more improved:

   - Without pattern: 14m4secs
   - With pattern: 15m 22secs

The additional time of 1m 18secs is still rather large, but definitely much more in line with expectations.

I think this patch is worthy of a new release! Thanks.

**Comment by feuerbach** [comment]
Great, released as 0.11.2.3.

**Comment by LeventErkok** [comment]
@feuerbach Awesome! Thanks..
