### ISSUE TITLE
Advice on picking tests?

### ISSUE THREAD

**Issue by LeventErkok** [feuerbach/tasty#178]
I've a test-suite with many test cases in it, about 350-thousand of them actually.

Usually I just want to run it all, and tasty works great. But in certain cases, I'd like to be able to tell tasty to run my test suite, but pick an arbitrary 20% of the tests based on a random number so I get a quick feedback on a random selection of tests. (Or some other percentage.)

(In reality, I want my tests to run on Travis: Unfortunately, travis machines are rather limited and they timeout when tests take too long. So if I can tell tasty to pick a certain percentage, I can make best use of Travis builds.)

Is there a way to do this with no (or minimal) change to the tests themselves? I was thinking of a solution along the lines of:

```haskell
reduceTests factor t = foldTestTree f mempty t
   where f = trivialFold { foldSingle = pick-if-random-number < factor
                         , foldGroup  = ???
                         }
```

But I'm not quite sure how to code `foldSingle`/`foldGroup`: In particular, I'll have to call for a random-number generator, so they'll have to either pass around a generator, or maybe be in the IO monad so I can use `randomRIO` and friends.

 Is this the right way to go? Any ideas/code snippets would be most appreciated.

**Comment by feuerbach** [comment]
Ha, that's a fun idea.

It's certainly possible to fold tests monadically; see e.g. the `foldTestTree` in `Test.Tasty.Run`. Sorry I don't have time to look closer, but you seem to be on the right track.

**Comment by LeventErkok** [comment]
@feuerbach 

I ended up with this code: https://github.com/LeventErkok/sbv/blob/master/SBVTestSuite/Utils/SBVTestFramework.hs#L119-L162

Seems to do the job! But if you can take a look and suggest any improvements, I'd love to hear!

Feel free to close this ticket, unless you want to keep it around as a feature request.

**Comment by feuerbach** [comment]
Yeah, that turned out to be not pretty...

Perhaps in this case it may be easier not to use `foldTestTree` and instead filter `TestTree` by recursively traversing it directly?

**Comment by LeventErkok** [comment]
Indeed, a direct filter is a lot cleaner: 

https://github.com/LeventErkok/sbv/blob/master/SBVTestSuite/Utils/SBVTestFramework.hs#L121-L136

This looks pretty idiomatic to me now, though I'd appreciate your feedback on it.

**Comment by feuerbach** [comment]
Looks good to me! It's a bit unfortunate that you cannot handle the three remaining types of nodes just as easily, but if you don't need them, it's fine.

**Comment by ulidtko** [comment]
Just to fix the links @LeventErkok gave, broken by master branch slide; corresponding permalinks are these:

* using `foldTestTree`: https://github.com/LeventErkok/sbv/blob/5984c148c1808ebd9d55087f14d74ddb8ecad5b7/SBVTestSuite/Utils/SBVTestFramework.hs#L119-L162
* using direct recursive walk: https://github.com/LeventErkok/sbv/blob/d51a87a9da222400dd7a928358ada9fa3d21e354/SBVTestSuite/Utils/SBVTestFramework.hs#L121-L136

The respective commit shows both examples side-by-side: https://github.com/LeventErkok/sbv/commit/d51a87a9da222400dd7a928358ada9fa3d21e354?diff=split

@UnkindPartition JFYI, I'm bumping the thread due to a similar need. Searching for examples of a TestTree traversal where the output Monoid is a TestTree again... Which turns out surprisingly nontrivial.

**Comment by Bodigrim** [comment]
I often wonder whether we shall refactor `TestTree` into
```haskell
data TestTreeF r 
  = forall t . IsTest t => SingleTest TestName t
  | TestGroup TestName [r]
  | PlusTestOptions (OptionSet -> OptionSet) r
  | forall a . WithResource (ResourceSpec a) (IO a -> r)
  | AskOptions (OptionSet -> r)
  | After DependencyType Expr r

type TestTree = Fix TestTreeF
```
so that we can use catamorphisms et al. from `recursion-schemes` / `data-fix`.
