### ISSUE TITLE
Quiet mode is hanging with large number of tests?

### ISSUE THREAD

**Issue by LeventErkok** [feuerbach/tasty#179]
For this program:

```haskell
module Main(main) where

import Test.Tasty
import Test.Tasty.HUnit

main = defaultMain tests

tests :: TestTree
tests = testGroup "tests"
           [testGroup ("testGroup" ++ show i)
                      [testCase (show i ++ "_" ++ show j) (j @?= j) | j <- [1 .. 3000]]
           | i <- [1 .. 10]
           ]
```

Compiled with `ghc -O2 -o a a.hs`, I get:

```
$ ./a --hide-successes

All 30000 tests passed (1.74s)
```

That took less than 2 seconds, which is great. Now I issue:

```
$ time ./a --quiet
^C
./a --quiet  122.98s user 1.12s system 98% cpu 2:05.41 total
```

I hit Ctrl-C after 2 minutes, and there seems to be no indication that tests are actually executing even though `top` suggests the process is running indeed.

I don't observe this when number of tests is small; so definitely something about large number of tests is in play here.

I'm on Mac OSX, if that makes any difference, with GHC 8.2.1.

**Comment by feuerbach** [comment]
Thanks for the report! Should be fixed on master:

```
% time ./a --hide-successes

All 30000 tests passed (1.76s)
./a --hide-successes  1.82s user 0.33s system 105% cpu 2.030 total

% time ./a --quiet
./a --quiet  0.80s user 0.11s system 101% cpu 0.888 total
```

I'll see if I can write some tests for this and then make a release, hopefully later this week. Does that work for you?

**Comment by LeventErkok** [comment]
Thanks for the quick fix! Yes; a week would be just fine. However, I do have another request: https://github.com/feuerbach/tasty/issues/180, which would be nice to look at first before a release.

**Comment by LeventErkok** [comment]
Now that #180 is done, this is not as urgent. Release whenever convenient. Thanks!
