### ISSUE TITLE
Quieter output from cabal test?

### ISSUE THREAD

**Issue by LeventErkok** [feuerbach/tasty#180]
I'm having the following issue with cabal tests that use tasty, running on CI (Travis). I'd like to know if there's a way to handle this properly, or perhaps tasty might be improved to handle this case.

When you have a large test suite that runs on Travis, and one of the tests towards the end fail, it is really hard to diagnose what went wrong. To wit, see this output:  http://travis-ci.org/LeventErkok/sbv/jobs/261686233

You'll have to scroll all the way to the bottom, and that does take a while! But when you do that, all you see is that Travis truncated the output because the tasty generated log file is way too long, and it cut off the part of the log file where the error occurred. (Travis allows you to download the raw log as well, but same problem: Since it's too large, it gets cut off.)

My tests script on Travis simply issues the following:

    cabal test SBVTest

Things I tried:

   * I tried `--hide-successes` with no success; the log file still contains all those lines causing Travis to truncate the output.
   * I tried `--quiet`: Unfortunately in this case there is no output at all, even when things fail, by design of course.

So, it seems I need a mode like `quiet`, but one that actually prints out the failure if they happen. Something like `--print-failures-only`, perhaps.

Is there a way to accomplish this? If not, would it be possible to support this mode?

Thanks!

**Comment by feuerbach** [comment]
Did you pass --hide-successes through cabal correctly? There should be a cabal option to pass arguments to the test.

Alternatively, you can set an environment variable; this is documented in the readme. (Sorry for no details; I'm on my phone.)

If you can't get it working, please write the commands that you tried and I'll try to look into it tomorrow.

**Comment by LeventErkok** [comment]
I had issues with passing arguments via cabal; so perhaps I screwed it up. I'll try with the env variable and see that helps; that sounds more promising. Thanks!

**Comment by LeventErkok** [comment]
The environment variable works! I must've screwed up passing the '--hide-successes' through cabal.

Thanks!

**Comment by feuerbach** [comment]
For the reference, the correct command-line syntax is 

```
cabal test --test-options=--hide-successes
```

```
    --test-option=TEMPLATE   give extra option to test executables (no need to
                             quote options containing spaces, name template can
                             use $pkgid, $compiler, $os, $arch, $test-suite)
```
