### ISSUE TITLE
Export contents of Test.Tasty.Ingredient.ConsoleReporter

### ISSUE THREAD

**Issue by merijn** [feuerbach/tasty#183]
I'm trying to write a wrapper around the consoleTestReporter to change behaviour when the tests run on a CI server. I'd like to fallback on the consoleTestReporter. I was hoping to be able to simply piggy-back my use of colour on the UseColor datatype, but since it's not exported I'm having to add a new flag to determine that. It'd be nicer/cleaner if I could use the same flags as consoleTestRunner so I don't have to add useless extra commandline flags.

**Comment by merijn** [comment]
Ok, I'm revising this issue to just exporting the contents of `Test.Tasty.Ingredient.ConsoleReporter`, as I'm finding myself copy+pasting large amounts of code from it directly into my own code, which seems a wasted code-reuse opportunity.

**Comment by merijn** [comment]
A more specific list of the stuff I'm copying/ripping off from ConsoleReporter so far:
`UseColor(..)`, `useColor`, `Statistics(..)`, `printStatistics`,`TestOutput(..)`,`produceOutput`, and
`foldTestOutput`

Not having to duplicate/reimplement these functions/datatypes would safe me a considerable amount of code and even more worry about keeping my local duplicate in sync with the upstream tasty code.

**Comment by feuerbach** [comment]
Hey Merijn,

I'd accept a PR that exports those types/functions, adding the docs where they are missing and the `@since` annotations.

**Comment by merijn** [comment]
Done, see #184. If I'm very motivated I might submit another PR to generalise the ConsoleReporter code to make it easier to dump it to a specified handle, rather than just stdout. But this is good enough for me to work with.

**Comment by feuerbach** [comment]
Thanks — just uploaded the new version.

**Comment by merijn** [comment]
Man, you are a hero for the turn-around time on that!
