### ISSUE TITLE
Missing link to documentup docs in read me

### ISSUE THREAD

**Issue by cj285** [feuerbach/tasty#185]
Is there a reason the documentup docs are no longer linked from the README?https://documentup.com/feuerbach/tasty

**Comment by feuerbach** [comment]
I don't remember what triggered the change — I think documentup was down at some point or something — but I've found documentup unnecessary for some time now. I think the github README works just fine. Does that affect you in some way?

**Comment by cj285** [comment]
No it doesn't. I was just wondering because I wasn't sure if they contained the same information. Thanks for the clarification!

**Comment by feuerbach** [comment]
Yes, they have always contained the same information — documentup is just a service that automatically generates a pretty page from a github readme.
