### ISSUE TITLE
Enable accessing test names from within tests?

### ISSUE THREAD

**Issue by iand675** [feuerbach/tasty#189]
I'm currently adding some webdriver tests to a test suite, and I'd like to take screenshots of failing test cases automatically and give them an appropriate file name so it's obvious which screenshot is associated with which test.

Unfortunately, there's not a way to really a good way to automate this well since ingredients don't have any way of knowing which tests are webdriver tests and which aren't.

I'd like to see a way to get at the test metadata within the test itself, perhaps something like `instance IsTest t => IsTest (TestName -> t)`, if that makes any sense.

**Comment by feuerbach** [comment]
Sorry, I don't understand what you're asking.

Ingredients have access to test names (as part of the test tree).
