### ISSUE TITLE
withResource releasing  is happening before last test

### ISSUE THREAD

**Issue by paolino** [feuerbach/tasty#190]
I'm running  this snippet
```
main = defaultMain
        $ withResource (return ()) (error "blam")
        $ const $ testGroup "g" [testCase "u1" (1 @?= 1), testCase "u2" (2 @?= 2)]
```
I expect both test pass before error is evaluated but

```
Progress: 1/2g
  u1: OK
  u2: FAIL
    Exception: blam
    CallStack (from HasCallStack):
      error, called at Bdd.hs:59:37 in main:Main

1 out of 2 tests failed (0.00s)
```

**Comment by feuerbach** [comment]
It's not happening *before* the last test, but it is happening *as part of* the last test after the body of that test completes. This is by design, to let you know your code does not work properly.

**Comment by paolino** [comment]
Thanks for explaanation . So the last test passed but I don't see it. Is there another coding pattern to use withResource I should use ?

**Comment by feuerbach** [comment]
I am not sure I understand the problem. Can you not fix your release action so that it does not throw an exception?

**Comment by paolino** [comment]
Well I'm writing a dsl which will compile to tasty so I'm not that author
of the release actions . I just have to deal with their possible exception
and not confuse the user.

**Comment by feuerbach** [comment]
You are giving me too few details to say anything useful. What is the scenario under which your release actions throw exception? What would you like to happen in that case?

If you want the exceptions to be silently dropped, just wrap them in try or catch and discard them.

**Comment by paolino** [comment]
I'm developing a BDD support so the idea is that *given* actions schedule
*andAfter* actions for when the test is done. I first decided to try
withResource for this.

I would like to see the results of all tests happening after the *given*
actions independently of the fact that any *andAfter* action would throw an
exception.
That's because the semantic of *andAfter* is that it has to be executed
after the tests and not in one of them.

I think it would be good to know if the exception have been thrown in the
test or in the releasing action.
This problem can be worked around  adding a non failing fake test as a last
one which will just prepend the *andAfter* actions.

BTW, rethinking of it, we decided to not abuse *withResource* for this but
try to roll our own provider. (https://github.com/paolino/tasty-bdd)
So we could just close the issue.
I humbly suggest this design should be well stated in the docs if it can be
considered unexpected for other users.

Thanks

2017-11-12 15:24 GMT+01:00 Roman Cheplyaka <notifications@github.com>:

**Comment by feuerbach** [comment]
Yeah, that's what I was going to suggest as well — it sounds like you want to write your own provider/ingredient to have finer control over the execution.

> I humbly suggest this design should be well stated in the docs if it can be considered unexpected for other users. 

If I see more confused users, I might do that, but your use case is a very special one, and most people will not care.
