### ISSUE TITLE
Make assertFailure return type polymorphic

### ISSUE THREAD

**Issue by themattchan** [feuerbach/tasty#191]
Is there any reason why `tasty-hunit` does not actually depend on `hunit`, but rather on a copy of the outdated `hunit-1.2`? How would the maintainers feel about a PR to update `tasty-hunit` to use the latest `hunit-1.6` (and add it as a proper dependency)? 

My reason for asking is that the new version of `hunit` has some minor API changes that I would like to use with the `tasty` framework.

**Comment by feuerbach** [comment]
> Is there any reason why tasty-hunit does not actually depend on hunit

The amount of code from hunit we were using was fairly minor, and so there's just no reason to depend on it.

> My reason for asking is that the new version of hunit has some minor API changes that I would like to use with the tasty framework.

What are they?

**Comment by themattchan** [comment]
`assertFailure :: String -> IO ()` has been changed to `assertFailure :: String -> IO a`

**Comment by feuerbach** [comment]
Yeah, I could get behind this one. I should also copy their call-stack integration.

**Comment by feuerbach** [comment]
The change is now in master. I'll probably make a release in a week or so.

**Comment by themattchan** [comment]
Thanks @feuerbach!
