### ISSUE TITLE
Change the `QuickCheckTests` value for a `TestTree` without invoking `IO`

### ISSUE THREAD

**Issue by recursion-ninja** [feuerbach/tasty#193]
I have a few tests that require more stochastic coverage than others. How do I specify that a `TestTree` has `QuickCheckTests = 5000` for all `QuickCheck` properties in it's sub-tree but not affect any other branches on the tree? I need to do this without involving `IO` so [`optionSetToArgs`](http://hackage.haskell.org/package/tasty-quickcheck-0.9.1/docs/Test-Tasty-QuickCheck.html#v:optionSetToArgs) looks rather useless. 

I was looking for something along these lines:

     modifyOptionInSubtree :: IsOption v => v -> TestTree -> TestTree

**Comment by feuerbach** [comment]
Take a look at <https://hackage.haskell.org/package/tasty-0.12/docs/Test-Tasty.html#v:localOption>

**Comment by recursion-ninja** [comment]
I should have searched the index better!
