### ISSUE TITLE
Make dependency on regex-tdfa optional

### ISSUE THREAD

**Issue by sjakobi** [feuerbach/tasty#195]
I noticed that removing the dependency on `regex-tdfa` would also remove the following transitive dependencies:

```
binary
bytestring
parsec
regex-base
regex-tdfa
text
```
If these dependencies were optional, tasty could be a very attractive test framework for core packages that wouldn't have to worry as much about circular dependencies.

My idea was to add a Cabal flag, e.g. `regex`, that toggles the regex support for the `--pattern` option. The alternative to the regex-based `--pattern` mechanism could be a simple substring-based mechanism, similar to `criterion`'s `pattern` or `ipattern`.

**Comment by sjakobi** [comment]
What would also be required to use `tasty` in a package like `containers` would be compatibility with `base-4.3`. Not sure if that's also feasible.

**Comment by feuerbach** [comment]
Yes, regex-tdfa is a long-standing PITA. I'd happily accept a PR to make it conditional. In the longer term, I'd also like to find the time to do #38, which would get rid of regex-tdfa unconditionally.

**Comment by feuerbach** [comment]
Re base-4.3, I'll look into it. Could you open a separate ticket for that?
