### ISSUE TITLE
Support base-4.3

### ISSUE THREAD

**Issue by feuerbach** [feuerbach/tasty#198]
Requested by @sjakobi in https://github.com/feuerbach/tasty/issues/195#issuecomment-353056585

**Comment by feuerbach** [comment]
@sjakobi: which test providers will you need with base-4.3? (e.g. hunit, quickcheck, smallcheck?)

**Comment by feuerbach** [comment]
To record my current progress on this:

* Building tasty with ghc 7.0 is currently blocked by #195 (regex-tdfa requires array >= 0.4, and ghc 7.0 ships with 0.3.0.2)
* Building tasty-hunit with ghc 7.0 is blocked by call-stacks.

My WIP is on the `base-4.3` branch.

**Comment by sjakobi** [comment]
Thanks for looking into this @feuerbach! :) I need the test providers for hunit and quickcheck.

**Comment by feuerbach** [comment]
Now that I've got rid of regex-tdfa, turns out that unbounded-delays doesn't build with base-4.3 (<https://travis-ci.org/feuerbach/tasty/builds/326423677>).
And I'm not sure what to do about call-stacks either.

So I'll call this exercise off; it seems to require more time and effort than I'm willing to spend on it.

Instead I can suggest the following: test that your project *builds* with base >= 4.3, but only *run the tests* with base >= 4.5. After all, it is very unlikely that a flaw in the logic of the code will only reveal itself with GHC 7.0/7.2 but not with the newer ghc versions. This is the strategy I use to test tasty itself: I only test with GHC >= 7.10 because I don't want to maintain compatibility ifdefs in the test code.
