### ISSUE TITLE
Add integration with 'type-spec'

### ISSUE THREAD

**Issue by ChShersh** [feuerbach/tasty#199]
I found this package quite useful for testing!

* https://github.com/sheyll/type-spec

Would be great to have integration between `tasty` and `type-spec`.

**Comment by feuerbach** [comment]
In tasty, integrations like this are called test providers and delegated to [third-party packages](https://github.com/feuerbach/tasty#providers).

If you or someone else creates one, I'll be happy to add it to the list.
