### ISSUE TITLE
Build failure with mtl-2.1.3.1

### ISSUE THREAD

**Issue by RyanGlScott** [feuerbach/tasty#200]
When building `tasty-1.0` on GHC 7.8.4, I ran into a build failure with `mtl-2.1.3.1`. An excerpt from the [Travis log](https://travis-ci.org/ku-fpg/natural-transformation/jobs/326668139#L676):

```
Test/Tasty/Patterns/Eval.hs:6:8:
    Could not find module ‘Control.Monad.Except’
    Perhaps you meant
      Control.Monad.Cont (from mtl-2.1.3.1)
      Control.Monad.Error (from mtl-2.1.3.1)
      Control.Monad.Compat (needs flag -package base-compat-0.9.3)
    Use -v to see a list of the files searched for.
```

**Comment by feuerbach** [comment]
Thanks for the report. I'm not sure why it picks mtl-2.1.3.1. I don't think it's caused by ghc 7.8.4 per se, because [my build](https://travis-ci.org/feuerbach/tasty/jobs/326415538) passes fine.

Anyway, I added a lower bound on hackage. Could you restart your build and see if it works now?

**Comment by RyanGlScott** [comment]
Thanks! The Travis build is [green](https://travis-ci.org/ku-fpg/natural-transformation) now, so I'll close this issue.
