### ISSUE TITLE
Utility library for tasks related to starting a service

### ISSUE THREAD

**Issue by kanishka-azimi** [feuerbach/tasty#206]
I don't know how much reuse is possible, but it would be nice to have a library with utility functions for starting and stopping a service, which tasty and hspec could rely on eventually.

My current use case is a typical web database application, where I have to start up a warp server. I know there is some prior work with hspec-wai, and there are some utilities for running actions before test startup in tasty.

Maybe this library could provide functions for:
- starting a wai-compatible server on a random port within a given range as a separate thread, returning the port selected
- stopping the server started
- repeat the two functions above, but for starting/stopping in a separate process instead of thread

I can add to this with more details as I implement the test suite I am writing currently, if desired. Feel free to close this if you would rather not address this functionality.

**Comment by feuerbach** [comment]
Anything dealing specifically with wai is definitely outside of scope of tasty. But it sounds to me that this can be a straightforward application of [resources](https://ro-che.info/articles/2013-12-10-tasty-resources) (starting/stopping the server thread/process).

You are welcome to write a separate library to provide the wai-related functionality, of course.
