### ISSUE TITLE
Test durations are invalid on x86_32

### ISSUE THREAD

**Issue by arybczak** [feuerbach/tasty#209]
Consider the following:

```haskell
module Main where

import Test.Tasty
import Test.Tasty.HUnit

main = defaultMain tests

tests :: TestTree
tests = testGroup "Tests"
  [ testCase "2+2=4" $
      2+2 @?= 4
  ]
```

When compiled on multilib x86_64 Gentoo Linux using 64bit GHC-8.0.2 and tasty-1.0.0.1, tasty-hunit-0.10.0.1, it produces the following output:

```
Tests
  2+2=4: OK

All 1 tests passed (0.00s)
```

However, when compiled on the same system using 32bit GHC-8.0.2 and tasty-1.0.0.1, tasty-hunit-0.10.0.1, it gives the following:

```
Tests
  2+2=4: OK (1831361170112512.00s)

All 1 tests passed (2768913876123648.00s)
```

**Comment by feuerbach** [comment]
Thanks for the report.

Could you try building tasty with the `clock` flag turned off and see whether it works then? (You'll have to look up how to set the flag depending on whether you use stack or cabal-install.)

**Comment by arybczak** [comment]
@feuerbach  Indeed it works fine with disabled clock flag.

**Comment by feuerbach** [comment]
I couldn't reproduce this on a plain i686 system, and my attempt to install a standard 32-bit binary release on a x86_64 system failed because of the hi magic number mismatch.

Could you give me access to a 64-bit machine with a working 32-bit ghc so that I could debug this issue?

**Comment by arybczak** [comment]
That might be a problem, I tested this on is my personal computer and I don't have access to any other environment like this :(

**Comment by feuerbach** [comment]
Could you give the instructions to reproduce this in a VM? Specifically, how to set up a x86_32 Gentoo and how to install ghc there.

**Comment by arybczak** [comment]
Full installation of Gentoo is pretty difficult to do as you need to set up a lot of things by hand, but it looks like things can be reproduced just by setting a chroot.

Below are the commands you need to execute that give you working 64bit Gentoo chroot with 32bit GHC able to compile and run the testcase:

```bash
# download gentoo snapshot
mkdir tasty-env
cd tasty-env
wget http://distfiles.gentoo.org/releases/amd64/autobuilds/20180311T214502Z/stage3-amd64-20180311T214502Z.tar.xz

# prepare chroot environment (as root)
tar pxxf stage3-amd64-20180311T214502Z.tar.xz
cd ..
cp -L /etc/resolv.conf tasty-env/etc/
mount -t proc /proc/ tasty-env/proc/
mount /sys/ tasty-env/sys/ -o bind
mount /dev/ tasty-env/dev/ -o bind
chroot tasty-env/

# go to /root
cd

# download portage
emerge-webrsync

# set up and install 32bit version of libgmp
echo "dev-libs/gmp abi_x86_32" > /etc/portage/package.use/gmp
emerge gmp -1

# set up and install 32bit version of ncurses
echo "sys-libs/ncurses:5 abi_x86_32 tinfo" > /etc/portage/package.use/ncurses5
emerge ncurses:5

# download and install 64bit haskell platform
mkdir platform
cd platform
wget https://haskell.org/platform/download/8.2.2/haskell-platform-8.2.2-unknown-posix--core-x86_64.tar.gz
tar xf haskell-platform-8.2.2-unknown-posix--core-x86_64.tar.gz
./install-haskell-platform.sh
cd ..

# update PATH
export PATH=/usr/local/bin:$PATH

# download and install 32bit ghc-8.0.2
wget https://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-i386-deb8-linux.tar.xz
tar pxxf ghc-8.0.2-i386-deb8-linux.tar.xz
cd ghc-8.0.2
CFLAGS=-m32 ./configure --prefix=/root/ghc32
make install
cd ..

# install dependencies for the testcase
cabal update
cabal install tasty-hunit --with-ghc=/root/ghc32/bin/ghc --ghc-options="-optc-m32 -opta-m32 -optl-m32"

# put the testcase in test.hs, compile and run it
ghc32/bin/ghc --make test.hs -optc-m32 -opta-m32 -optl-m32
./test
```

**Comment by feuerbach** [comment]
Thanks — can reproduce it now.

**Comment by feuerbach** [comment]
Here's what's happening:

* The fields of `struct timespec` are 64-bit on 64-bit arch, 32-bit on 32-bit arch.
* The clock package uses hsc2hs to substitute the correct sizes/offsets/types for the current architecture.
* You pass `--ghc-options="-optc-m32 -opta-m32 -optl-m32"` to ghc to use the 32-bit types, but hsc2hs does not know about that and continues to use the 64-bit types.

The fix is to pass `--hsc2hs-options="-C -m32 -L -m32"` to `cabal install` in addition to the other options.

**Comment by arybczak** [comment]
Oh well, that's unfortunate :/ Sorry for the mess then.

**Comment by feuerbach** [comment]
Hey, no worries, hope it helped.
