### ISSUE TITLE
sensei for tasty?

### ISSUE THREAD

**Issue by fisx** [feuerbach/tasty#210]
I love using [hspec/sensei](https://github.com/hspec/sensei) to get the time between save and getting the failing test case down to a second or two (with a few additional tricks, admittedly).  the idea is simple enough: ghcid runs in the background and watches the sources of your project, reloads on change, and feeds the output to a unix domain socket where you can fetch it into your IDE.

Is anybody working on something like that for tasty?

**Comment by feuerbach** [comment]
Not that I know of. We discussed something similar in #153, I think. So feel free to build it if you are interested.

**Comment by fisx** [comment]
Ah, thanks for the reference.  I also thought of a work-around I like: you can write an hspec wrapper around the tasty test suite and use sensei on that.
