### ISSUE TITLE
Display failing test messages after the suite is done

### ISSUE THREAD

**Issue by parsonsmatt** [feuerbach/tasty#213]
I'm looking at this right now:

![image](https://user-images.githubusercontent.com/7310112/36957003-a28d6018-1fee-11e8-9133-6a8d2ada4cb0.png)

And the test failure itself has disappeared off of my scrollback. Can `tasty` reproduce the failing error message(s) at the end of the test suite?

**Comment by feuerbach** [comment]
You can use `--hide-successes` to only display the errors.

You could also easily write a console reporter that would repeat the errors at the end if you want.

**Comment by parsonsmatt** [comment]
`--hide-successes` only mutes the green `OK` in the output; that the test ran is still present, and the scrollback is still huge. This is what I get doing `stack test --test-arguments "--hide-successes"` in the PureScript repo:

![image](https://user-images.githubusercontent.com/7310112/36995376-1939d516-2071-11e8-9ae9-e4a3ce1fd78f.png)

Is that expected behavior?

**Comment by feuerbach** [comment]
No, that's not the expected behavior. From looking at the purescript repo, they/you are using `Test.Tasty.Hspec` — I suspect that to be the culprit. Try tasty-hunit instead?

**Comment by feuerbach** [comment]
Of course this may be a drastic change to the purescript test suite. You probably should file a bug for tasty-hspec.

**Comment by parsonsmatt** [comment]
Yup, I'll file the bug over there :)
