### ISSUE TITLE
Broken bounds for tasty 0.11 and 0.12

### ISSUE THREAD

**Issue by merijn** [feuerbach/tasty#214]
tasty 0.11 and 0.12 have a `< 5` bound on base, sadly they're broken with base-4.11 as there is a missing Semigroup instance for OptionSet. Earlier versions are unaffected due to a bound of `base < 4.9`. Ideally all tasty versions of 0.11.* and 0.12.* should be amended with a revision specifying `base < 4.11`

**Comment by feuerbach** [comment]
I appreciate the issue but don't have the resources to maintain the past versions.

**Comment by gwils** [comment]
In my capacity as a hackage trustee, I've revised these versions as merijn correctly identified. I've also revised some other versions: I've added an upper bound of `either < 4.6` to tasty-0.6 and tasty-0.7, and an upper bound of `unbounded-delays < 0.1.1` to the tasty-0.8.* series.

**Comment by feuerbach** [comment]
Thanks @gwils.
