### ISSUE TITLE
Space leak in tasty 1.2

### ISSUE THREAD

**Issue by peti** [feuerbach/tasty#234]
Hi,

I've been running the test suite for [`cabal2nix`](https://github.com/NixOS/cabal2nix) successfully with a 1K stack limit for the longest time, but now I am suddenly experiencing crashes because the test program exceeds that limit. For example, see @danburton's bug report at https://github.com/NixOS/cabal2nix/issues/398. I've verified that the program works just fine with `tasty-1.1.0.4`, but once I build it with `tasty-1.2`, things go haywire:

~~~
cabal2nix-2.12: test (suite: regression-test)
            
Progress 1/2: cabal2nix-2.12regression-test: Stack space overflow: current size 33624 bytes.
regression-test: Use `+RTS -Ksize -RTS' to increase it.
~~~~

Note that the required stack space has gone *way up*. According to the profiling data, the stack trace at the time of the crash is:

~~~
*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
  Test.Tasty.Options.Env.myLookupEnv,
  called from Test.Tasty.Options.Env.getEnvOptions.lookupOpt,
  called from Test.Tasty.Runners.Reducers.mappend,
  called from Test.Tasty.Options.Env.getEnvOptions,
  called from Test.Tasty.Options.Env.suiteEnvOptions,
  called from Test.Tasty.CmdLine.defaultMainWithIngredients,
  called from Test.Tasty.defaultMain,
  called from Main.main
*** Exception (reporting due to +RTS -xc): (THUNK_STATIC), stack trace: 
  Test.Tasty.Run.checkCycles.sccs,
  called from Test.Tasty.Run.checkCycles,
  called from Test.Tasty.Run.resolveDeps,
  called from Test.Tasty.Run.createTestActions.mb_tests,
  called from Test.Tasty.Run.createTestActions,
  called from Test.Tasty.Run.launchTestTree,
  called from Test.Tasty.Ingredients.tryIngredient,
  called from Test.Tasty.Ingredients.tryIngredients.\,
  called from Test.Tasty.Ingredients.tryIngredients,
  called from Test.Tasty.CmdLine.defaultMainWithIngredients,
  called from Test.Tasty.defaultMain,
  called from Main.main
~~~

Do you have any idea how I might be able to remedy this issue? 

Best regards,
Peter

**Comment by feuerbach** [comment]
Hi Peter,

Could you provide a minimal example that exhibits the issue? I seem to be able to run a dummy test suite with 8 tests with `+RTS -K1K`, so it's probably not something on the surface.

**Comment by peti** [comment]
> Could you provide a minimal example that exhibits the issue?

No, I don't think I can easily do that. The test suite for cabal2nix is
pretty simply and straight-forward, though. I am sorry that I can't be
more helpful at the moment.

**Comment by feuerbach** [comment]
It appears that the cause is stronglyConnComp from Data.Graph. If you comment the guard [here](https://github.com/feuerbach/tasty/blob/dc9d2bb1097db5d6a7a06a8eb4859586b5aee38d/core/Test/Tasty/Run.hs#L344), then your suite passes with 1K. (I also checked that it's stronglyConnComp itself, and not the graph construction forced by stronglyConnComp.)

I don't see any evidence of an actual space leak here.

**Comment by peti** [comment]
OK. Thank you very much for taking the time to investigate this phenomenon. And also thank you very much for maintaining this fine library and for release it as free software!
