### ISSUE TITLE
cursor remains hidden on interrupt

### ISSUE THREAD

**Issue by joeyh** [feuerbach/tasty#237]
Tasty hides the cursor, and when I interrupt it, the cursor remains hidden. I am not using the defaultMain, but am driving tryIngredients.

Looks like the signal handler to restore the cursor is only set up when using defaultMainWithIngredients and installSignalHandlers is not exposed.

**Comment by feuerbach** [comment]
installSignalHandlers is now exposed in master. Please give it a try, and if it works for you, I can make a release.

**Comment by feuerbach** [comment]
(It is exposed via Test.Tasty.Runners)
