### ISSUE TITLE
Tweaking shrinking behavior

### ISSUE THREAD

**Issue by m-alvarez** [feuerbach/tasty#242]
Hi, I'm looking for a command line flag that would allow me to tweak the behavior of the QuickCheck shrinker in the same way that I can use `--hedgehog-shrinks` with `tasty-hedgehog`, is there any way to do this?

**Comment by feuerbach** [comment]
Does that control the number of shrinks? There doesn't seem to be an option atm, but it should be straightforward to add — feel free to send a PR.
