### ISSUE TITLE
[question] Progress reporting

### ISSUE THREAD

**Issue by mankyKitty** [feuerbach/tasty#243]
I'm having a crack at reimplementing the progress reporting with moderate success... The `hedgehog` package reports progress and `tasty-hedgehog` hooks into that, which is part of the driver for my efforts.

I can maintain the cursor position so the progress updates simply refresh that one position, and most things still line up, but if the timing is off then the cursor position gets a little messed up:

I'm using `saveCursor` and `restoreCursor` to refresh the text at the result position.

Just wondering if people had any thoughts on this? I can push up a fork if that helps... Just hacking for now.
```
        OK
    bytestring gen - via text encoder/decoder
      unicode:                                           OK (0.16s)100%
        OK
      latin1:                                            OK (0.14s)100%
        OK
      ascii:                                             OK (0.13s)100%
        OK
  Json 'Prisms'' must OBEY THE LAW: (preview p (review p x) == Just x)
    _Bool:                                               OKnning : 100%
      OK
    _Number:                                             OKnning : 28%%
      OK
    _TextJson:                                           OK (0.38s)100%
      OK
    _String:                                             OKnning : 31%%
      OK
    Json array prism
      _ArrayOf Scientific:                               OKRunning : 1% (0.05s)
Running : 2%                                                       OK
Running : 3%      _ArrayOf Text:                           OKRunning : 1% (0.59s)
Running : 2%                                                       OK
Running : 3%      _ArrayOf Bool:                           OKnning : 100%
        OK
      _ArrayOf Json:                                     OK (9.23s)100%
        OK
```
The extra `OK` on the subsequent line comes from `tasty-hedgehog`, that's not a problem at the moment.

**Comment by feuerbach** [comment]
Are you trying to report progress directly from tasty-hedgehog?

There's a progress hook in tasty. It's not used at the moment, but if you're looking at it, I'd recommend to go that route — i.e. make it so that tasty (specifically, the console ingredient) itself prints the progress when the hook is called.

**Comment by mankyKitty** [comment]
It's the `yieldProgress` hook in tasty in `Test.Tasty.Run` that I'm tinkering with, that's what you're referring to? Just checking that we're talking about the same thing. :)

I managed to sort of kinda fix my formatting issue, but adding a 1ms delay before printing the `Result` of the test. But that's a bit awful so I'll try to work out something better.

Feel free to close this and I'll open a PR if I work out a reliable solution. :)

**Comment by feuerbach** [comment]
> It's the `yieldProgress` hook in tasty in `Test.Tasty.Run` that I'm tinkering with, that's what you're referring to? Just checking that we're talking about the same thing. :)

Correct. Are you trying to print from the callback itself? That wouldn't work because tests are executing in parallel. The correct way is for the callback to update a TVar and for the ConsoleReporter module to monitor that TVar and print the updates. All output should be done by ConsoleReporter from its own thread.

**Comment by feuerbach** [comment]
(Or if I'm guessing incorrectly, you can open a draft PR and I could take a look.)
