### ISSUE TITLE
group test together in HUnit

### ISSUE THREAD

**Issue by chantisnake** [feuerbach/tasty#248]
Hi I kind of want the effect like quick check. 
For a test group: 
1. If there is any test failed, then the whole group fails
2. Do not display the individual test case, unless it fails
3. When a test case fails, the group stops running.

We are using tasty to do homework grading, this feature will be really useful.
I have noticed that in HUnit, there is TestList that can kind of do that (except it do not stop when there is one error encountered).

I was wondering is there any functionality that tasty provide that are similar to that?

**Comment by feuerbach** [comment]
There's a `--hide-successes` flag that satisfies (2).

But what you describe sounds very much like a simple HUnit case.

E.g.

```
testCase "test group 1" $ do
  assertion1
  assertion2
  assertion3
```

If assertion2 fails, then assertion3 won't be run, and the whole "group" will fail.

**Comment by chantisnake** [comment]
Thank you so much!

**Comment by feuerbach** [comment]
Yes, it only prints the assertion that fails.

**Comment by chantisnake** [comment]
Thank you so much.
