### ISSUE TITLE
Expose computeStatistics from Ingredients.ConsoleReporter

### ISSUE THREAD

**Issue by bollu** [feuerbach/tasty#251]
This is similar to #183, but I wish to expose more of the internals. 

In particular, I want to expose `computeStatistics`. There is `Statistics` exposed, as well as `printStatistics`, but not `computeStatistics`.

This is for a custom ingredient that shortens test case outputs when printing, but serializes the full test case to disk ([here is a link to the ingredient](https://github.com/tweag/asterius/pull/125/files#diff-e5a74906999b7f2b20abb90223c90eb0R201))

Would a PR that exposes this function be acceptable?

Thanks a lot!

**Comment by feuerbach** [comment]
Sure, go ahead.
