### ISSUE TITLE
Add ability to blacklist test cases based on pattern?

### ISSUE THREAD

**Issue by bollu** [feuerbach/tasty#254]
Just as there is the option to whitelist test cases based on a pattern, I'd also like the ability to blacklist certain test cases based on a pattern. 

A scenario where this is useful is for when there's a "mysteriously failing" test case, and one wishes to skip this test during CI, but wishes to debug this test case locally. In this case, one would use the blacklist on the CI and the whitelist locally.

Would this be accepted as a PR?

**Comment by feuerbach** [comment]
It should be already possible: `--pattern '! /mypattern/'`

**Comment by bollu** [comment]
Ah, great! I don't know `awk` well - it's nice to know that it has blacklisting. Thanks for the help.

**Comment by feuerbach** [comment]
Sure — there's also a table of supported operators [here](https://github.com/feuerbach/tasty#patterns).
