### ISSUE TITLE
Control which tests are run by test name?

### ISSUE THREAD

**Issue by bollu** [feuerbach/tasty#256]
I have a collection of tests which I wish to run, that do _not logically_ belong to a `TestGroup`. Many of them are failing, so I wish to only run a subset of them on my CI. 

Ideally, I'd like to add a CLI option (or extend the `--pattern` syntax) where I can choose an _arbitrary subset of tests_ I wish to run by name. As far as I can tell, such an option does not exist in `tasty`. 

Is there a reasonable way to add this to `tasty`? Or am I supposed to use `tasty` differently, when I want to have the full testsuite, but only run an arbitrary subset on the CI? As in, is it expected that I will perform the filtering myself when constructing the `TestGroup`?

I'm trying to get a feeling for where tasty's boundaries lie, philosophically, and asking if there would be interest in adding such an option to tasty's core.

**Comment by feuerbach** [comment]
You could say `--pattern '/foo/ || /bar/ || ...'`. This should allow you to choose an arbitrary subset of tests.

**Comment by bollu** [comment]
Ah. I thought that "Type of result: Numeric" meant that this could only be used for numeric checks. I should have realized that a pattern is accepted or failed based on whether the value is `1` or `0`.  If it was labeled `boolean`, I might have realized this.

Thanks for the help :)
