### ISSUE TITLE
  --quickcheck-verbose doesn't work

### ISSUE THREAD

**Issue by TheAussieStew** [feuerbach/tasty#257]
As described in the documentation, I'm compiling my tests like so:
```
main = do
    setEnv "TASTY_QUICKCHECK_VERBOSE" "true"
    defaultMain tests
```

But this produces the following error.
`*** Exception: Bad environment variable TASTY_QUICKCHECK_SHOW_REPLAY='true' (parsed as option quickcheck-show-replay)`

It works fine if I use these numerical arguments:
`
setEnv "TASTY_NUM_THREADS" "1"
` 

But not for this boolean argument:
`
setEnv "TASTY_HIDE_SUCCESSES" "true"
`

**Comment by feuerbach** [comment]
I cannot reproduce this. Which versions of tasty and tasty-quickcheck are you getting this with? Could you try the latest versions?
