### ISSUE TITLE
What is the default number of threads

### ISSUE THREAD

**Issue by dnadales** [feuerbach/tasty#259]
I don't know whether this is a silly questions, but the help states:

```
  -j,--num-threads NUMBER  Number of threads to use for tests execution
```

however I cannot find (in the docs or in the code) what is the default number of threads to be used. Is it 1? And is it worth documenting this? 

Thanks!

**Comment by feuerbach** [comment]
I updated the docs to explain this. The default is the number of GHC capabilities (which itself by default is the number of available cores but [can be overridden](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-concurrent.html#rts-flag--N%20%E2%9F%A8x%E2%9F%A9)).

**Comment by dnadales** [comment]
Great! Thanks!
