### ISSUE TITLE
--quickcheck-tests should override withMaxSuccess

### ISSUE THREAD

**Issue by sjakobi** [feuerbach/tasty#260]
I have some tests defined like

```
tests :: TestTree
tests =
    Test.Tasty.QuickCheck.testProperties
        "QuickCheck"
        [ ( "My property"
          , Test.QuickCheck.property (Test.QuickCheck.withMaxSuccess 1000 myProp)
          )
        ]
```
I use `withMaxSuccess`, as QuickCheck never finds any interesting cases with 100 tests.

Sometimes I want to get even more test cases and run my testsuite with `--quickcheck-tests 5000`. But that doesn't seem to override the value from `withMaxSuccess`:

```
      +++ OK, passed 1000 tests.
```

Can this behaviour be changed within `tasty-quickcheck` or `QuickCheck`? Or can I fix this within my test setup?

**Comment by feuerbach** [comment]
Instead of `withMaxSuccess` (which I don't think can be overridden from the outside), I suggest you use [adjustOption](https://hackage.haskell.org/package/tasty-1.2.3/docs/Test-Tasty.html#v:adjustOption). Then you can take your command-line setting and, say, apply `max 1000` to it.

**Comment by sjakobi** [comment]
Thank you, that's very helpful! :+1: 

I now realize though, that instead of passing in an _absolute_ number of tests with `--quickcheck-tests`, I'd prefer to supply a _multiplier_. The reason is that some properties are slower than others and a number of tests that's appropriate for some properties, might overly increase the runtime of others. Could something like `--quickcheck-tests-multiplier` or `--quickcheck-tests-factor` be added?

**Comment by feuerbach** [comment]
Sure, you can define a [custom option](https://github.com/feuerbach/tasty#custom-options) for that.

**Comment by sjakobi** [comment]
:+1: I might just try that.

Thanks for all the help and the lovely library! :)
