### ISSUE TITLE
Allow numeric underscores for --quickcheck-tests

### ISSUE THREAD

**Issue by sjakobi** [feuerbach/tasty#263]
I sometimes want to execute so many tests that I struggle to read the numbers I'm writing.

Instead of 

    --quickcheck-tests 10000000

I would like to write

    --quickcheck-tests 10_000_000

or maybe

    --quickcheck-tests 10,000,000

**Comment by feuerbach** [comment]
Sorry for a long delay.

**Comment by sjakobi** [comment]
No worries! Thanks a lot! :)
