### ISSUE TITLE
Make displaying defaultValue in --help output more idiomatic

### ISSUE THREAD

**Issue by RyanGlScott** [feuerbach/tasty#269]
`tasty` has an `IsOption` class that abstracts the details of how command-line options are handled. One thing is currently does not do is handle how [`defaultValue`](https://hackage.haskell.org/package/tasty-1.2.3/docs/Test-Tasty-Options.html#v:defaultValue)s are displayed in the `--help` output. As a result, this is usually tacked on to the end of `optionHelp` manually. Here are three examples from `tasty` alone:

https://github.com/feuerbach/tasty/blob/79132dd4f270e2bb6804c7d6dcdf8d5d07d204a4/core/Test/Tasty/Options/Core.hs#L38
https://github.com/feuerbach/tasty/blob/79132dd4f270e2bb6804c7d6dcdf8d5d07d204a4/core/Test/Tasty/Ingredients/ConsoleReporter.hs#L461
https://github.com/feuerbach/tasty/blob/79132dd4f270e2bb6804c7d6dcdf8d5d07d204a4/core/Test/Tasty/Ingredients/ConsoleReporter.hs#L485-L488

It would be nice to specify this information declaratively. In fact, `optparse-applicative` has a [`showDefaultWith`](https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative.html#v:showDefaultWith) combinator for this very purpose. Alas, we can't just use that: `showDefaultWith` only works when used in conjunction with the [`value`](https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative.html#v:value) combinator, and `value` [does not play nicely with `tasty`'s environment variable detection](https://github.com/feuerbach/tasty-golden/issues/37).

Perhaps we can accomplish the same end result without `value`/`showDefaultWith`, however. Here is one proposal for how to go about this:

1. Add a new method to `IsOption`:

   ```hs
   class IsOption v where
     ...
     optionHelpDefault :: v -> Maybe String
     optionHelpDefault _ = Nothing
   ```

   If `optionHelpDefault` returns `Just m`, the `--help` output will display `(default: <m>)` after the `optionHelp` text. If it returns `Nothing`, only the `optionHelp` text will be displayed.
2. In order to make `optparse-applicative` actually display `optionHelpDefault`, we'll need to change [`propShowDefault`](https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative-Types.html#v:propShowDefault) accordingly. It's tempting to think that [`optionMod`](https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative-Builder-Internal.html#v:optionMod) would suffice to accomplish this, but in practice, that gets overwritten based on the values in [`DefaultProp`](https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative-Builder-Internal.html#t:DefaultProp). A possible alternative to modify the final `Parser` after it is built.
3. Finally, to ensure that we don't accidentally shoot ourselves in the foot, we should outlaw the use of `value` in `optionCLParser`. This, too, might be possible by inspecting the final `Parser` after it is built.

   We might consider having a similar check for any uses of `showDefaultWith`, although if we implement this correctly, the effects of `showDefaultWith` will simply be ignored altogether.

Does this sound like a reasonable design, @feuerbach?

**Comment by feuerbach** [comment]
Yep, looks good. I'd just think a bit more about the name; `optionHelpDefault` does not make obvious to me what it does. Perhaps `showDefaultValue`?

**Comment by RyanGlScott** [comment]
I made a brief attempt at implementing this, but I didn't get very far. The part at which I became stuck was step (2)—namely, modifying the final `Parser` after it is built. The challenge is that I need to write a function like this:

```hs
finalizeCLParser :: IsOption v => Parser v -> Parser v
```

Where [`Parser`](https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative-Types.html#t:Parser) is defined like so:

```hs
data Parser a
  = NilP (Maybe a)
  | OptP (Option a)
  | forall x . MultP (Parser (x -> a)) (Parser x)
  | AltP (Parser a) (Parser a)
  | forall x . BindP (Parser x) (x -> Parser a)
```

The cases for `OptP`, `NilP`, and `AltP` are quite straightforward:

```hs
finalizeCLParser (OptP o) = OptP (modifyTheOptions o)
finalizeCLParser p@NilP{} = p
finalizeCLParser (AltP p1 p2) = AltP (finalizeCLParser p1) (finalizeCLParser p2)

-- Modify the OptProperties here using IsOption's showDefaultValue
modifyTheOptions :: IsOption v => Option a -> Option a
```

Things get trickier in the `MultP` and `BindP` cases, which involve existentially quantified type variables. If you try to implement `finalizeCLParser` for `MultP` in the naïve way, for instance,

```hs
finalizeCLParser (MultP pf px) = MultP (finalizeCLParser pf) (finalizeCLParser px)
```

You won't be able to know that the existentially quantified `x` has an `IsOption` instance:

```
Test/Tasty/CmdLine.hs:41:41: error:
    • Could not deduce (IsOption (x -> v))
        arising from a use of ‘finalizeCLParser’
        (maybe you haven't applied a function to enough arguments?)
      from the context: IsOption v
        bound by the type signature for:
                   finalizeCLParser :: forall v. IsOption v => Parser v -> Parser v
        at Test/Tasty/CmdLine.hs:36:1-64
    • In the first argument of ‘MultP’, namely ‘(finalizeCLParser pf)’
      In the expression:
        MultP (finalizeCLParser pf) (finalizeCLParser px)
      In an equation for ‘finalizeCLParser’:
          finalizeCLParser (MultP pf px)
            = MultP (finalizeCLParser pf) (finalizeCLParser px)
   |
41 | finalizeCLParser (MultP pf px) = MultP (finalizeCLParser pf) (finalizeCLParser px)
   |                                         ^^^^^^^^^^^^^^^^^^^

Test/Tasty/CmdLine.hs:41:63: error:
    • Could not deduce (IsOption x)
        arising from a use of ‘finalizeCLParser’
      from the context: IsOption v
        bound by the type signature for:
                   finalizeCLParser :: forall v. IsOption v => Parser v -> Parser v
        at Test/Tasty/CmdLine.hs:36:1-64
      Possible fix:
        add (IsOption x) to the context of the data constructor ‘MultP’
    • In the second argument of ‘MultP’, namely ‘(finalizeCLParser px)’
      In the expression:
        MultP (finalizeCLParser pf) (finalizeCLParser px)
      In an equation for ‘finalizeCLParser’:
          finalizeCLParser (MultP pf px)
            = MultP (finalizeCLParser pf) (finalizeCLParser px)
   |
41 | finalizeCLParser (MultP pf px) = MultP (finalizeCLParser pf) (finalizeCLParser px)
   |                                                               ^^^^^^^^^^^^^^^^^^^
```

You'll run into similar trouble with `BindP`. One possible workaround is to simply not recur into `MultP` and `BindP` at all. I worry that this approach would be fragile, however, since it means that any `Parser` that was constructed in an applicative or monadic fashion might fail to have its underlying `Option`s updated properly.

Out of curiosity, I looked to see if there was an existing function in `optparse-applicative` itself that performing this sort of `Option`s mapping. The closest thing I could find was [`mapParser`](https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative-Common.html#v:mapParser), but that maps a `Parser a` to a `[a]`, not to another `Parser a`.

**Comment by feuerbach** [comment]
Are you trying to modify the parser returned by `optionParser`?

If, instead, you modify the parser returned by `optionCLParser` before it gets mixed with other options, you'll know what option that parser is for, and you can call IsOption methods on that option. Your function's type would then be something like `finalizeCLParser :: IsOption v => Proxy v -> Parser u -> Parser u`.

**Comment by RyanGlScott** [comment]
> If, instead, you modify the parser returned by `optionCLParser` before it gets mixed with other options, you'll know what option that parser is for, and you can call IsOption methods on that option.

I'm worried that this approach isn't robust enough. Consider:

```hs
newtype File = MkFile String
instance IsOption File where
  ...
  optionCLParser = pure MkFile <*> strOption (metavar "FILE")
```

This implementation of `optionCLParser` would return `MultP (NilP (Just MkFile)) (OptP <option>)`, and once you run into `MultP`, you're stuck. Granted, none of the `IsOption` instances in `tasty` itself appear to use the `Applicative` instance for `Parser`, but that doesn't mean that no such instances exist outside of `tasty` itself.

 > Your function's type would then be something like `finalizeCLParser :: IsOption v => Proxy v -> Parser u -> Parser u`.

I'm confused. If we're modifying the result of `optionCLParser`, then shouldn't it be `Parser v -> Parser v`, not `Parser u -> Parser u`?

**Comment by feuerbach** [comment]
> I'm confused. If we're modifying the result of `optionCLParser`, then shouldn't it be `Parser v -> Parser v`, not `Parser u -> Parser u`?

No — my point was that if you use the `IsOption` instance for the known option (the one you call `optionCLParser` for), you then can make your function fully parametric in the type argument of `Parser` (here denoted by `u`), and therefore *not* be stuck at `MultP` points.

**Comment by RyanGlScott** [comment]
If I understand you correctly, you're suggesting that when we reach an `OptP` node, just invoke `showDefaultWith` to obtain a `Maybe String`, and then modify `propShowDefault` (which itself is a `Maybe String`) accordingly? In the `File` example in https://github.com/feuerbach/tasty/issues/269#issuecomment-620875170, that would mean that we would be using the `IsOption File` instance to modify an `Option String`—in effect, modifying something of a completely different type. That's a bit strange, but I suppose it would work out in the end, since `File`'s `optionCLParser` is just a thin wrapper around a `Parser String`.

I worry that this approach would provide yet another way for users to shoot themselves in the foot. Namely, if they write an `optionCLParser` that contains multiple `OptP`s, like so:

```hs
data FilePair = MkFilePair String String

instance IsOption FilePair where
  ...
  optionCLParser = MkFile
    <$> strOption ...
    <*> strOption ...
```

Then `finalizeCLParser` would modify _every_ `OptP` in the `Parser`, which is almost assuredly not what they want. In practice, I can't imagine that many people are doing such a thing, since `IsOption` is intended to encapsulate a single option, but it is technically possible. Perhaps this is a sign that we should add another validity check: if an `optionCLParser` contains more than one `OptP`, then throw an error?

**Comment by feuerbach** [comment]
> If I understand you correctly, you're suggesting that when we reach an `OptP` node, just invoke `showDefaultWith` to obtain a `Maybe String`, and then modify `propShowDefault` (which itself is a `Maybe String`) accordingly?

Exactly (assuming by `showDefaultWith` you mean our new method and not the modifier from optparse-applicative)

> In the `File` example in [#269 (comment)](https://github.com/feuerbach/tasty/issues/269#issuecomment-620875170), that would mean that we would be using the `IsOption File` instance to modify an `Option String`—in effect, modifying something of a completely different type. That's a bit strange, but I suppose it would work out in the end, since `File`'s `optionCLParser` is just a thin wrapper around a `Parser String`.

Right — the logic is that this is a parser for the option File, and so it should display the default value for the option File.

> I worry that this approach would provide yet another way for users to shoot themselves in the foot. Namely, if they write an `optionCLParser` that contains multiple `OptP`s, like so:
> 
> ```haskell
> data FilePair = MkFilePair String String
> 
> instance IsOption FilePair where
>   ...
>   optionCLParser = MkFile
>     <$> strOption ...
>     <*> strOption ...
> ```
> 
> Then `finalizeCLParser` would modify _every_ `OptP` in the `Parser`, which is almost assuredly not what they want.

Yeah, we don't support such parsers. I wouldn't say it's a problem with this approach per se — your original approach, even if it wasn't ruled out by the type system, wouldn't work here either, because the Strings themselves are not options.

> In practice, I can't imagine that many people are doing such a thing, since `IsOption` is intended to encapsulate a single option, but it is technically possible. Perhaps this is a sign that we should add another validity check: if an `optionCLParser` contains more than one `OptP`, then throw an error?

Agreed — although in all these cases, I'd prefer just to print a warning. I don't think these issues are serious enough to warrant an error (in case someone is already doing this, we don't want their code to break suddenly), and a warning will probably be noticed by the author when they test their new option.

**Comment by RyanGlScott** [comment]
I've submitted a (mostly complete) PR at #270, although there are still some minor TODOs to be addressed.
