### ISSUE TITLE
Run TestTree without command line options parsing?

### ISSUE THREAD

**Issue by locallycompact** [feuerbach/tasty#272]
Hi, sorry if this is documented anywhere but I couldn't find it. I'm trying to run a tasty golden test from behind a shake rule, but using `defaultMain` is intercepting the command line options that shake is using so I get this.

```
[nix-shell:~/Source/gitlab.com/shakebook-site/shakebook-site.gitlab.io]$ shake test
2020-06-06 15:13:17.228604: [info] Cleaning files in public/
@(Shakefile.hs:320:8)
Invalid argument `test'

Usage: Shakefile.hs [-p|--pattern PATTERN] [-t|--timeout DURATION] 
                    [-l|--list-tests] [-j|--num-threads NUMBER] [-q|--quiet] 
                    [--hide-successes] [--color never|always|auto] 
                    [--ansi-tricks ARG] [--accept] [--no-create] 
                    [--size-cutoff n]
Error when running Shake build system:
  at want, called at src/Development/Shake/Internal/Args.hs:83:67 in shake-0.19-A0TFR49dYLPBrSFt2xiNXa:Development.Shake.Internal.Args
* Depends on: test
* Raised the exception:
ExitFailure 1
```

Is it possible to turn this off and just run the test case with liftIO somehow?

**Comment by feuerbach** [comment]
I think [tryIngredients](https://hackage.haskell.org/package/tasty-1.3.1/docs/Test-Tasty-Ingredients.html#v:tryIngredients) is what you want.

You can pass it `defaultIngredients` (or any other list) and whatever options you'd like it to run with.
