### ISSUE TITLE
Pick up CLI options outside of IsTest 

### ISSUE THREAD

**Issue by alexbiehl** [feuerbach/tasty#274]
I am working on a more or less complex combinator that is supposed to wrap around tests. Think about it like 

```
withDockerContainers :: (forall m. MonadDocker m => m a) -> (IO a -> TestTree) -> TestTree
``` 

Internally I am using `withResource` and let Tasty handle all the goodness of resource allocation/de-allocation. Now, I would really love to be able to expose command line arguments via Tasty's IsOption mechanism to allow configuration of various things. But since I am 

* wrapping around other tests 
* relying on withResource 

I kinda do not fit the options framework in Tasty nor the `IsTest` interface.  I have thought about a possible solution: 

Tasty collects the available options on startup by traversing the `TestTree` using `treeOptions`. Usages of `askOption` could be picked up along the way and added to the set of available options. So that I could write something along the lines of 

```
withDockerContainers :: (forall m. MonadDocker m => m a) -> (IO a -> TestTree) -> TestTree
withDockerContainers containers tests = 
  askOption $ \ (MySpecialOption x) ->
    withResource (allocate x containers) release tests
```

and have Tasty expose the corresponding CLI parameter by the usage of `askOption` .

I would be happy to implement if we reach a conclusion.

**Comment by feuerbach** [comment]
If you know which options you need, you can use <https://hackage.haskell.org/package/tasty-1.3.1/docs/Test-Tasty-Ingredients-Basic.html#v:includingOptions> to register them outside of IsTest.

What you are suggesting is also possible, but would (1) require breaking changes to the TestTree type and (b) would still be a hack, as the options used by the tests may potentially depend on which options you pass into them in the first place — though it would probably work fine in practice.

**Comment by alexbiehl** [comment]
`includingOptions` sounds like it would work! Thanks!
