### ISSUE TITLE
Include Auto-Discovery Tool with Tasty

### ISSUE THREAD

**Issue by EarthCitizen** [feuerbach/tasty#275]
Can an auto-discovery tool be included with Tasty itself? As can be seen below, the options for this are no longer maintained. To me, it seems logical to include something like this in Tasty, being optional to use of course.

### **tasty-auto:**

https://github.com/minad/tasty-auto

```
Deprecated: Auto discovery for the Tasty test framework, use tasty-discover instead

github.com/lwm/tasty-discover
```
### **tasty-discover:**

https://git.coop/decentral1se/tasty-discover

```
 Archived project! Repository and other project resources are read only
```

**Comment by feuerbach** [comment]
Whether or not it's included in tasty is a red herring — the real question is who is going to maintain it.

I understand your frustration as a user, and I know you mean well, but please understand that to me your question essentially reads as "Can you commit to putting unpaid labor into maintaining this piece of code that you didn't write and don't use yourself?" 

Perhaps you could take over the maintenance of one of those two packages yourself instead?

**Comment by EarthCitizen** [comment]
"No" would have sufficed.

**Comment by sjakobi** [comment]
@EarthCitizen There seems to be an active fork of `tasty-discover` at https://github.com/waddlaw/tasty-discover.

(CC @waddlaw)

**Comment by EarthCitizen** [comment]
@feuerbach  As an FYI, hspec includes its own discovery tool.

@sjakobi Thanks
