### ISSUE TITLE
Access OptionSet in 'TreeFold.foldGroup' 

### ISSUE THREAD

**Issue by fendor** [feuerbach/tasty#276]
I want to access the OptionSet in `TreeFold.foldGroup` for a custom test-reporter.
Afaict, this is currently not possible
I came up with three possible solutions:

* Add `OptionSet` as a parameter to `TreeFold.foldGroup`
  * Breaking Change
* Add a field to `TreeFold` where you can basically access the OptionSet
  * Something like `foldPlusOptions :: OptionSet -> b -> b`
  * Feels a bit awkward
* Wire it somehow through the state in the fold. 
  * Result might be inaccurate afaict. 

--- 

My motivation is to use/abuse `tasty` to work as a test-suite and grading system for students at the same time. I hope to gain from this an easy way to run tests for students, a big ecosystem to write tests in (e.g. tasty-golden, etc...) and a practical introduction into haskell testing.

The envisioned syntax is:
```
main :: IO ()
main = defaultMainWithIngredients [jsonRunner] unitTests

unitTests :: TestTree
unitTests = groupPoints 3 0 5 $  testGroup "Unit tests"
  [ testCase "List comparison (different length)" $
      [1, 2, 3] `compare` [1,2] @?= GT

  -- the following test does not hold
  , testCase "List comparison (same length)" $
      [1, 2, 3] `compare` [1,2,2] @?= LT
  ]
```

where the results are written as json for later processing.
E.g.
```json
{
  "results": [
    {
      "groups": [
        {
          "points": 
           {
              "plus": 3,
              "minus": 0,
              "upperBound": 5
           }, 
          "groups": [
            {
              "time": "0.000",
              "name": "List comparison (different length)",
              "classname": "Tests.Unit tests"
            },
            {
              "time": "0.000",
              "name": "List comparison (same length)",
              "failure": "test/MyLibTest.hs:20:\nexpected: LT\n but got: GT",
              "classname": "Tests.Unit tests"
            }
          ],
          "tests": 2,
          "name": "Unit tests"
        }
      ],
      "tests": 2,
      "name": "Tests"
    }
  ],
  "tests": 2,
  "time": "0.000",
  "failures": 1,
  "errors": 0
}
```

**Comment by feuerbach** [comment]
Indeed, the intended way is to "wire it somehow through the state in the fold" — specifically, instantiate `b` in `TreeFold b` with `OptionSet -> b'`. What do you mean when you say the result may be inaccurate?

**Comment by fendor** [comment]
I am probably mainly struggling with the implementation. This looks very helpful, thank you!

**Comment by fendor** [comment]
I am probably mainly struggling with the implementation. This looks very helpful, thank you!

**Comment by fendor** [comment]
I am struggling with the implementation. Is there an example on how the code would look like?

**Comment by feuerbach** [comment]
Sorry, I didn't realize `TreeFold` had fallen behind `TestTree`. It should have the field corresponding to `PlusTestOptions`, then you'd be able to implement your function.

**Comment by feuerbach** [comment]
Ah, never mind, I misremembered what the function does. You were right, it's not a simple fold, it tries to keep track of the options.

So I guess the right solution would be to add the OptionSet argument to foldGroup (and other fields as well). Would you make a PR?

**Comment by fendor** [comment]
Yes, I am happy to attempt a PR!
