### ISSUE TITLE
tasty-smallcheck-0.8.2 does not build with GHC 7.8

### ISSUE THREAD

**Issue by Bodigrim** [feuerbach/tasty#291]
https://github.com/Bodigrim/smallcheck/runs/1713686905?check_suite_focus=true#step:16:215
```
Test/Tasty/SmallCheck.hs:104:10:
    No instance for (Typeable Finish)
      arising from the superclasses of an instance declaration
    In the instance declaration for ‘Exception Finish’
```
I can raise a PR, if you wish. In the meantime it would be nice to revise the lower bound of `base` to avoid unbuildable plans.

**Comment by feuerbach** [comment]
Should be fixed now, thanks.

**Comment by Bodigrim** [comment]
If it is not too much trouble, could you please also revise earlier `tasty-smallcheck-0.8` releases with `base >= 4.5`? Earlier `base`s impose `Show a => Num a`, which is not satisfied by https://github.com/feuerbach/tasty/blob/23d856cdce96dd71b825490da30b4338a4f0a582/smallcheck/Test/Tasty/SmallCheck.hs#L28-L29

**Comment by feuerbach** [comment]
Sure, done.
