### ISSUE TITLE
Duplicate command-line options

### ISSUE THREAD

**Issue by Bodigrim** [feuerbach/tasty#292]
if there is more than one `TestReporter` then `--help` lists `-j,--num-threads` several times:

https://github.com/feuerbach/tasty/blob/23d856cdce96dd71b825490da30b4338a4f0a582/core/Test/Tasty/Ingredients.hs#L108-L115

Similarly, if the same command-line option is shared between several providers / ingredients, it ends up reported multiple times as well:

https://github.com/feuerbach/tasty/blob/23d856cdce96dd71b825490da30b4338a4f0a582/core/Test/Tasty/Ingredients.hs#L119-L123

Cf. https://github.com/Bodigrim/tasty-bench/issues/3

I'm happy to raise a PR fixing this, but unsure about approach. Should we try to preserve the order of options? Or throwing everything in a `Set` and getting back alphabetically sorted will do?

**Comment by feuerbach** [comment]
Let's try to preserve the order. We could use something [like this](https://github.com/feuerbach/regex-applicative/blob/master/Text/Regex/Applicative/StateQueue.hs).
