### ISSUE TITLE
Richer pattern language

### ISSUE THREAD

**Issue by feuerbach** [feuerbach/tasty#38]
Including `&&`, `||` , and `!`.

Things to think about:
- syntax and escaping
- do we want to be able to set options based by regex? E.g. for everything matching `foo` set the depth to 20. Not sure it's worth the effort.

See also #36.

**Comment by utdemir** [comment]
Hey, 

I need this feature, solely for specifying a list of tests to run. But my proposal would be just adding a `-r | --regex-pattern` option for specifying tests via a pattern.

I can try implementing this if `-r` option is okay.

What do you think?

**Comment by feuerbach** [comment]
There's already `--pattern`.

**Comment by utdemir** [comment]
Assuming we have four tests, named `A`, `B`, `C` and `D`.

The `--pattern` paremeter don't allow one to specify "`A` and `B`, but not `C` and `D`". But if tasty had a `--regex-pattern` option, one could easily have said `(A|B)`.

**Comment by feuerbach** [comment]
Ah, I see what you mean. The question is, what the regex should be applied to.

**Comment by utdemir** [comment]
I was thinking a search on full path. For example, when the test is "a/b/c/d":

    ^a/b/c/d
    b/c
    a/.*/d
    /d$

should all match.

**Comment by feuerbach** [comment]
Using `/` as a separator is somewhat problematic. In tasty-golden it is common to name tests after golden file paths which may contain slashes.

Likewise, using `.` as a separator would clash with the regex syntax.

**Comment by utdemir** [comment]
But there would still be old `pattern` option, since it's simplier and easier on most cases. `tasty-golden` users or users which have special chars on their test names can just use the old version.

**Comment by phile314** [comment]
Thumbs up on this, I need something like regex syntax as well.

The problem with tasty-golden seems difficult to solve properly, as unix filepaths can contain almost any characters. I agree that using '/' could be unwise, so a less common character might be better. What about '>'?

**Comment by phile314** [comment]
As this already has been an open issue for a long time, I will be so free to link to my own package here.I really needed this badly, so I just added this to my [tasty-silver](http://hackage.haskell.org/package/tasty-silver-3.1.5) package (fork of tasty-golden).

It provides an (experimental) --regex-include/--regex-exclude option, and uses '/' as seperator at the moment. In my solution, it's also possible to give these options multiple times. If somebody else wants to try it out, you can just use the defaultMain from [Test.Tasty.Silver.Interactive](http://hackage.haskell.org/package/tasty-silver-3.1.5/docs/Test-Tasty-Silver-Interactive.html).

A way forward for the tasty package itself may be to add support for specifying "--pattern" multiple times? This would at least solve the use case where one wants to disable known failing tests without completely removing them.

**Comment by suleymanozarslan** [comment]
Dear @feuerbach, 
I also need this feature, could you help us?

**Comment by feuerbach** [comment]
@suleymanozarslan can you describe your use case?

**Comment by suleymanozarslan** [comment]
I have around 3000 numbered test cases, like “threats/234324”, “threats/121312”, “threats/545678” and sometimes I just want to play a few threats. Just repeatedly calling tasty is not an option because most of the testGroups have initialisation routines taking a long time.
I just want to test a few test case
I want to be able to specify something like “234324 | 123456”

**Comment by feuerbach** [comment]
Requirements for the new pattern language that I've heard so far:

1. Logical operators (`&&`, `||`, `!`)
2. Apply equality tests and proper regexes to individual test/group names as well as the full test path
3. Good performance on ~30k tests
4. Don't depend on regex-tdfa or other slow to compile languages

(Other relevant tickets: #130, #164, #175.)

My current thinking is to implement an AWK-like DSL, so you could say `-p '$1 == "Foo" || $3 ~ /Bar$/'`.

The simplest pattern would be `-p '/foo/'`, or even `-p foo`.  If a pattern `X` does not contain any of the special symbols, treat it as `/X/`.

I am still undecided about what to use for regex matching.  I considered pcre-light as an alternative to regex-tdfa, but apparently [it's a pain to build on Windows](https://stackoverflow.com/q/26288139/110081).

What do people think?

**Comment by Profpatsch** [comment]
> What do people think?

Isn’t that context-free by design?

**Comment by feuerbach** [comment]
@Profpatsch what do you mean?

**Comment by Profpatsch** [comment]
Parsing a string DSL with operators sounds context-free to me.

**Comment by feuerbach** [comment]
Regex matching is part of the language itself and not a means to parse the language, if that is what you are referring to. Otherwise I'm still not sure what your point is.

**Comment by Profpatsch** [comment]
Then I misread. I thought you wanted to parse the language with a regex library.

**Comment by cartazio** [comment]
My testing needs are simple enough that anything is probably fine

**Comment by LeventErkok** [comment]
I should say that I'm a recent convert to tasty and I am a big fan. Before tasty, I had a homegrown solution, which was literally falling apart. Tasty is so much better. Thanks!

I wanted to chime in though regarding patterns. Like @cartazio my use case is also very simple. Indeed `isInfixOf pat testName` would suffice for me, no regular expressions needed at all. I can see the use of multiple (or-like) patterns, but that can be done via `-p pat1 -p pat2` without adding anything new?

My needs are probably much simpler than what other people have, but I'd humbly suggest keeping it as simple as possible, focusing on performance. I find that people overuse regexps sometime when a simple wildcard would more than suffice, but that's just my experience.

Again, thanks for this fantastic piece of software. Extremely useful!

**Comment by feuerbach** [comment]
Glad you like it, Levent!

I also like simplicity, but as you can see from this issue, there is demand for more features.

I'd like to consider the option of avoiding regexes though — especially given that I see no good regex library options.

The simplest version is not to allow any metacharacters at all. `/foo/` means a test whose path contains `foo`.

#130 is addressed by awk-like expression, `$2 == "Foo"`, instead of `$2 ~ /^Foo$/`.

Any objections to this simplification?

**Comment by LeventErkok** [comment]
One alternative would be to go like grep where you can give fixed patterns via the `-f` flags.

For instance, `-fpat` might mean fixed-strings (like grep's `-f`), which can be used by #138 I think, and the regular `-pat` would be just wildcards with an implicit surrounding `*`. (i.e., `-pat foo` would mean match `*pat*`, wile `-fpat foo` would mean match exactly `foo`.  But perhaps that's too simplistic.

**Comment by feuerbach** [comment]
I am glad to report that the work on the new awk patterns is almost finished!

It is on the `new-patterns` branch. Please take a look at the [docs](https://github.com/feuerbach/tasty/blob/new-patterns/README.md#patterns), give it a try, and let me know what you think.

The remaining tasks from my perspective are:

1. Add some built-in string functions
2. Implement a pruning optimization and measure performance

I hope to release this within a week or two.

**Comment by feuerbach** [comment]
See <https://ro-che.info/articles/2018-01-08-tasty-new-patterns>
