### ISSUE TITLE
Use the clock package

### ISSUE THREAD

**Issue by feuerbach** [feuerbach/tasty#98]
See http://chrisdone.com/posts/measuring-duration-in-haskell

**Comment by LukeHoersten** [comment]
Is the plan here to time each test? That feature doesn't exist yet does it?

**Comment by feuerbach** [comment]
Each test separately, and the test suite as a whole. It does exist already, except individual timings aren't printed when they are less than 10ms, so if your tests are fast enough, you won't notice it.

**Comment by LukeHoersten** [comment]
Awesome thanks.
