### ISSUE TITLE
Feature request: a way to disable a test or a group of tests a la JUnit's @Ignore annotation

### ISSUE THREAD

**Issue by manzyuk** [feuerbach/tasty#99]
It would be nice to have a combinator ```ignore :: TestTree -> TestTree``` (or perhaps ```ignore :: String -> TestTree -> TestTree```) with an effect similar to that of JUnit's ```@Ignore``` annotation.

**Comment by feuerbach** [comment]
Can you explain? I have no idea what `@Ignore` does.

**Comment by manzyuk** [comment]
The annotation does what the name suggests: it disables a test, so that it
is not run by the test harness. Ignored tests are mentioned by the summary
report as such. In particular, they are not reported as failing if they are
broken.

This does not sound like a lot, but it can be pretty convenient when doing
major code surgeries to temporarily disable known failures. You can also
optionally specify a reason a given test is disabled.

I find this approach to be a more convenient way to disable tests than by
commenting out code: in JUnit you simply add @Ignore before a test
definition to disable it. Commenting out code is particularly tedious if
you build with -Wall -Werror and have to also comment out other definitions
that become unused or redundant imports.

**Comment by feuerbach** [comment]
What about `ignore = const $ testGroup "Ignored tests" []`?

**Comment by manzyuk** [comment]
This does allow one to quickly disable a test or a group of tests, but it messes up the reporting.  I'd like the ignored tests to be reported as such, not to be replaced by an empty group of tests, so that when I look at a report (generated say by a CI server), I know exactly which tests are passing, which are failing, and which are ignored and for what reason.

**Comment by feuerbach** [comment]
I believe @nomeata is addressing this in his new package, see #114

**Comment by nomeata** [comment]
Uploaded as http://hackage.haskell.org/package/tasty-expected-failure, contains `ignoreTest`.
